from __future__ import annotations


def seo_guides() -> list[dict]:
    return [
        {
            "slug": "how-much-concrete-for-a-4-inch-slab",
            "title": "How Much Concrete Do I Need for a 4-Inch Slab?",
            "category": "Concrete Planning",
            "topic": "concrete",
            "parent": "concrete-slab-calculator",
            "description": "Learn how to estimate concrete for a 4-inch slab, convert cubic feet to cubic yards, and add a practical waste allowance.",
            "answer": "For a rectangular slab, multiply length by width by 4 inches converted to feet. Divide the cubic-foot result by 27 to get cubic yards, then add a project-specific allowance for waste and uneven subgrade. The calculation estimates material quantity; slab thickness, reinforcement and subgrade design are separate decisions.",
            "steps": [
                ("Measure the slab", "Use the actual finished length and width in feet and split irregular shapes into simple rectangles."),
                ("Convert 4 inches", "Four inches equals 4 ÷ 12 = 0.3333 ft."),
                ("Calculate volume", "Multiply length × width × thickness to get cubic feet, then divide by 27 for cubic yards."),
                ("Add allowance", "Apply a visible allowance for waste, grade variation and ordering practice rather than hiding it in the formula."),
            ],
            "formula": "cubic yards = length(ft) × width(ft) × 0.3333 ÷ 27",
            "example": "A 20 ft × 30 ft slab at 4 inches is about 20 × 30 × 0.3333 = 200 ft³, or 7.41 yd³ before an ordering allowance.",
            "mistakes": "Do not assume a nominal 4-inch slab will be exactly 4 inches everywhere. Do not use the concrete quantity calculation to choose structural thickness or reinforcement. Confirm the supplier's minimum order and truck-delivery rules before purchasing.",
            "faqs": [
                ("Is 4 inches enough for a slab?", "Thickness depends on use, loads, soil, reinforcement and applicable design requirements; the calculator only converts dimensions to volume."),
                ("How much extra concrete should I order?", "A modest allowance is common for estimating, but the right amount depends on grade variation, form accuracy, access and supplier minimums."),
                ("Should I order by cubic feet or yards?", "Ready-mix suppliers commonly quote concrete by cubic yard, so convert the calculated cubic feet to cubic yards."),
            ],
        },
        {
            "slug": "4-inch-vs-5-inch-vs-6-inch-concrete-slab",
            "title": "4-Inch vs 5-Inch vs 6-Inch Concrete Slab: Quantity Comparison",
            "category": "Concrete Planning",
            "topic": "concrete",
            "parent": "concrete-slab-calculator",
            "description": "Compare how slab thickness changes concrete volume and why thickness should be selected from project requirements rather than material cost alone.",
            "answer": "For the same footprint, concrete volume increases directly with slab thickness. A 5-inch slab uses 25% more concrete than a 4-inch slab, while a 6-inch slab uses 50% more. That is a quantity comparison, not a recommendation for structural thickness.",
            "steps": [
                ("Keep the footprint constant", "Compare thicknesses using the same length and width."),
                ("Convert thickness to feet", "Divide inches by 12 before multiplying by area."),
                ("Compare volumes", "Volume changes in direct proportion to thickness when the footprint stays the same."),
                ("Separate quantity from design", "Use drawings, soil information, intended loads and qualified design guidance to select thickness."),
            ],
            "formula": "volume ratio = new thickness ÷ original thickness",
            "example": "Moving from 4 inches to 5 inches changes the volume ratio to 5 ÷ 4 = 1.25, so the same footprint requires 25% more concrete.",
            "mistakes": "Choosing slab thickness only because one option is cheaper, ignoring subgrade preparation, or treating a volume comparison as structural engineering advice.",
            "faqs": [
                ("How much more concrete is 6 inches than 4 inches?", "For the same footprint, 6 inches requires 50% more concrete than 4 inches."),
                ("Does thicker always mean stronger?", "Thickness is only one part of performance. Subgrade, reinforcement, concrete properties, joints and loading also matter."),
                ("Can I use this comparison for a driveway?", "It can compare material quantities, but driveway thickness and reinforcement should follow the project's load and site requirements."),
            ],
        },
        {
            "slug": "concrete-driveway-material-estimate-guide",
            "title": "Concrete Driveway Material Estimate Guide",
            "category": "Concrete Planning",
            "topic": "concrete",
            "parent": "concrete-driveway-calculator",
            "description": "Estimate concrete for a driveway by breaking the footprint into sections and keeping thickness, waste and ordering assumptions visible.",
            "answer": "Estimate driveway concrete by calculating the area of each section, multiplying by the planned thickness, converting the total to cubic yards and adding a practical ordering allowance. Driveways need more than a volume calculation: subgrade, drainage, joints, reinforcement and load requirements must also be considered.",
            "steps": [
                ("Break the driveway into sections", "Use rectangles or other simple shapes for the main run, apron and widened areas."),
                ("Use the planned thickness", "Convert inches to feet before calculating volume."),
                ("Convert to supplier units", "Add the section volumes, then divide cubic feet by 27 to get cubic yards."),
                ("Plan the order", "Consider waste, grade variation, truck access, minimum load charges and whether the pour can be completed continuously."),
            ],
            "formula": "yd³ = total area(ft²) × thickness(ft) ÷ 27",
            "example": "A 12 ft × 40 ft driveway at 5 inches has 480 ft² × 0.4167 ft = about 200 ft³, or 7.41 yd³ before allowance.",
            "mistakes": "Using the driveway's centerline length without accounting for widening, forgetting the apron, ordering exactly the calculated volume despite uneven grade, and selecting thickness without considering the intended vehicle loads.",
            "faqs": [
                ("Does a driveway need a different calculation from a slab?", "The basic volume formula is the same, but driveway planning has additional load, subgrade, drainage and joint considerations."),
                ("Should I include the apron?", "Yes. If it will be poured as part of the project, measure and calculate it as a separate section."),
                ("Can the calculator design the driveway?", "No. It estimates material volume only and does not replace site-specific design."),
            ],
        },
        {
            "slug": "concrete-waste-and-ordering-allowance-guide",
            "title": "Concrete Waste Allowance: How Much Extra Should You Order?",
            "category": "Concrete Planning",
            "topic": "concrete",
            "parent": "concrete-waste-calculator",
            "description": "Understand why calculated concrete volume and actual ready-mix orders can differ, including grade variation, forms and supplier minimums.",
            "answer": "A mathematical volume is a starting point, not a guaranteed delivered quantity. Actual requirements can change because of uneven subgrade, over-excavation, form movement, spillage, pump or chute losses and measurement uncertainty. Use an explicit allowance and confirm the supplier's ordering policy.",
            "steps": [
                ("Calculate theoretical volume", "Use measured dimensions and the intended thickness."),
                ("Review measurement quality", "Irregular excavation and varying depth create more uncertainty than a perfectly formed rectangle."),
                ("Choose an allowance", "Use a project-specific percentage rather than assuming one universal number fits every pour."),
                ("Check supplier rules", "Confirm minimum loads, truck capacity, short-load fees, delivery timing and cancellation terms."),
            ],
            "formula": "order volume = theoretical volume × (1 + allowance percentage)",
            "example": "If the theoretical quantity is 8.0 yd³ and the planning allowance is 7%, the estimate becomes 8.56 yd³ before checking supplier rounding and minimum-load rules.",
            "mistakes": "Treating the allowance as a substitute for accurate measurement, using the same percentage for every project, or forgetting that ready-mix suppliers may sell in increments or minimum loads.",
            "faqs": [
                ("Is 10% always the correct allowance?", "No. Allowance should reflect the quality of measurements, grade variation, access and project conditions."),
                ("Does waste mean concrete is actually wasted?", "It is a planning allowance for uncertainty and losses; good estimating can reduce unused material."),
                ("Should I round up the final order?", "Follow the supplier's ordering increments and minimum-load rules after calculating the project quantity."),
            ],
        },
        {
            "slug": "asphalt-driveway-tonnage-estimate-guide",
            "title": "Asphalt Driveway Tonnage Estimate Guide",
            "category": "Driveways & Paving",
            "topic": "roofing-decks-fences",
            "parent": "asphalt-calculator",
            "description": "Estimate asphalt tonnage from paved area, compacted thickness and material density while keeping density assumptions editable.",
            "answer": "Calculate asphalt volume from area and compacted thickness, then multiply by an appropriate density to estimate weight. Because asphalt mix density varies by mix and supplier, use the supplier's current ton-per-cubic-yard or density information whenever available.",
            "steps": [
                ("Measure paved area", "Calculate the driveway, parking area or path footprint in square feet."),
                ("Enter compacted thickness", "Use the design thickness and convert inches to feet."),
                ("Calculate volume", "Area × thickness gives cubic feet; divide by 27 for cubic yards."),
                ("Apply density", "Multiply volume by the selected density and convert the result to short tons when required."),
            ],
            "formula": "tons = area(ft²) × thickness(ft) × density(lb/ft³) ÷ 2,000",
            "example": "A 600 ft² area at 3 inches has 150 ft³ of compacted volume. At an illustrative 145 lb/ft³ density, the estimate is about 10.88 short tons.",
            "mistakes": "Using loose delivery thickness as if it were compacted thickness, assuming every asphalt mix has the same density, and ignoring the base and drainage design beneath the asphalt.",
            "faqs": [
                ("What density should I use?", "Use the asphalt supplier's current mix density when available; the default in a calculator is only an estimating assumption."),
                ("Is thickness before or after compaction?", "Use the thickness specified by the project or supplier and make sure it is clear whether it is compacted thickness."),
                ("Does this calculate the pavement structure?", "No. It estimates asphalt material quantity; base, drainage and pavement design are separate."),
            ],
        },
        {
            "slug": "paver-patio-material-estimate-guide",
            "title": "Paver Patio Material Estimate Guide",
            "category": "Landscaping",
            "topic": "landscaping",
            "parent": "paver-base-calculator",
            "description": "Plan pavers, base aggregate and bedding material separately for a patio while accounting for cuts, layout waste and compaction.",
            "answer": "A paver patio estimate has at least three material layers: the pavers themselves, the compacted base and the bedding layer. Calculate the surface area first, then calculate each layer from its own installed depth. Paver waste is usually driven by the layout and cutting pattern, while base quantities need a compaction allowance.",
            "steps": [
                ("Calculate patio area", "Split complex shapes into simple rectangles and triangles where needed."),
                ("Estimate pavers", "Use the manufacturer's coverage per pallet, bundle or square foot and add a layout-specific cutting allowance."),
                ("Estimate base", "Multiply area by the specified base depth and convert to cubic yards; account for compaction according to the material and supplier."),
                ("Estimate bedding material", "Keep bedding depth separate from the structural base depth and follow the paver system instructions."),
            ],
            "formula": "layer volume(yd³) = area(ft²) × depth(ft) ÷ 27",
            "example": "A 300 ft² patio with a 6-inch base has 150 ft³, or 5.56 yd³, of in-place base volume before the material-specific compaction allowance.",
            "mistakes": "Counting paver thickness as base depth, applying one waste percentage to every material, and ordering loose aggregate equal to the compacted volume without checking the supplier's guidance.",
            "faqs": [
                ("How much paver waste should I allow?", "It depends on the pattern, borders, cuts and the shape of the patio. Complex patterns usually need more planning allowance."),
                ("Is base depth the same as bedding depth?", "No. They perform different functions and should be calculated separately."),
                ("Can this be used for a vehicle area?", "It can estimate quantities, but the base and pavement system for vehicle loads needs project-specific design."),
            ],
        },
    ]
