from __future__ import annotations


def seo_guides() -> list[dict]:
    return [
        {
            "slug": "how-many-80lb-bags-of-concrete-do-i-need",
            "title": "How Many 80-lb Bags of Concrete Do I Need?",
            "category": "Concrete Planning",
            "topic": "concrete",
            "parent": "concrete-bag-calculator",
            "description": "Estimate the number of 80-lb premixed concrete bags for small slabs, posts, footings and repair jobs using published yield instead of guessing from weight alone.",
            "answer": "Bag count should be calculated from the project's volume divided by the manufacturer's yield per bag. Bag weight alone does not tell you the finished concrete volume because dry ingredients, aggregate grading and product formulation affect yield.",
            "steps": [
                ("Calculate project volume", "Use length × width × depth for a rectangular pour and convert inches to feet."),
                ("Find the product yield", "Use the current bag label or manufacturer data for yield per 80-lb bag."),
                ("Divide volume by yield", "Convert project volume to the same unit used by the yield, then divide and round up."),
                ("Plan extra bags", "Keep a visible allowance for uneven excavation, small spills and the possibility of a second mixing batch."),
            ],
            "formula": "bags = required volume ÷ yield per bag",
            "example": "If a product yields 0.60 ft³ per 80-lb bag and the project needs 12 ft³, 12 ÷ 0.60 = 20 bags before an allowance.",
            "mistakes": "Using a generic yield for a different product, assuming every 80-lb bag yields the same volume, or rounding down because the theoretical result is close to a whole bag.",
            "faqs": [
                ("Does every 80-lb bag make the same amount of concrete?", "No. Yield varies by product formulation, aggregate and manufacturer."),
                ("Should I buy exactly the calculated number?", "For small pours, round up and consider an allowance because a shortage can be difficult to correct after the pour begins."),
                ("Can I use this for structural concrete?", "The quantity estimate can help with planning, but product selection and structural requirements must follow the project specifications."),
            ],
        },
        {
            "slug": "concrete-footing-volume-estimate-guide",
            "title": "Concrete Footing Volume Estimate Guide",
            "category": "Concrete Planning",
            "topic": "concrete",
            "parent": "concrete-footing-calculator",
            "description": "Calculate rectangular and continuous footing concrete volume while keeping footing geometry separate from structural design.",
            "answer": "For a rectangular footing, multiply footing length by width by depth. For a continuous footing, calculate each run separately when widths or depths change, then add the volumes and convert cubic feet to cubic yards. The calculator estimates material only; footing dimensions must come from the project design.",
            "steps": [
                ("Measure each footing run", "Separate different widths, depths or stepped sections instead of averaging them blindly."),
                ("Convert all dimensions", "Use one unit system and convert inches to feet before multiplying."),
                ("Calculate volume", "Length × width × depth gives cubic feet for a rectangular section."),
                ("Convert and order", "Divide total cubic feet by 27 and review waste, forms, excavation variation and supplier minimums."),
            ],
            "formula": "footing volume(ft³) = length(ft) × width(ft) × depth(ft); yd³ = ft³ ÷ 27",
            "example": "A 40 ft continuous footing that is 1.5 ft wide and 0.5 ft deep contains 30 ft³, or 1.11 yd³, before an allowance.",
            "mistakes": "Using excavation dimensions as finished concrete dimensions, averaging stepped footings without checking each section, and treating the quantity calculation as footing design.",
            "faqs": [
                ("Should I calculate each footing separately?", "Yes when dimensions differ. It reduces errors and makes the estimate easier to audit."),
                ("Do footings need reinforcement?", "That depends on the design. Reinforcement is not determined by this volume calculation."),
                ("How do I order small footing quantities?", "Check the ready-mix supplier's minimum-load and short-load policies after calculating the theoretical volume."),
            ],
        },
        {
            "slug": "cubic-yard-conversion-guide-concrete-and-aggregate",
            "title": "Cubic Yards Conversion Guide for Concrete and Aggregate",
            "category": "Construction Planning",
            "topic": "concrete",
            "parent": "cubic-yard-calculator",
            "description": "Convert cubic feet to cubic yards and understand why volume conversion is different from converting aggregate to tons.",
            "answer": "One cubic yard contains 27 cubic feet. Divide cubic feet by 27 to convert volume to cubic yards. Converting cubic yards to tons requires a density assumption, so it is a separate calculation and should use the supplier's material density whenever possible.",
            "steps": [
                ("Calculate cubic feet", "Use the project's length, width and depth in feet."),
                ("Divide by 27", "This converts cubic feet to cubic yards."),
                ("Keep density separate", "Only convert volume to weight after selecting an appropriate material density."),
                ("Check product data", "Aggregate suppliers may quote material by ton, cubic yard or both; use their current conversion information."),
            ],
            "formula": "cubic yards = cubic feet ÷ 27",
            "example": "A 10 ft × 20 ft × 0.5 ft layer is 100 ft³, which equals 100 ÷ 27 = 3.70 yd³.",
            "mistakes": "Dividing by 12 instead of 27, treating a cubic-yard measurement as square yards, or assuming a universal tons-per-yard conversion for every aggregate.",
            "faqs": [
                ("Why is one cubic yard 27 cubic feet?", "A yard is 3 feet in each dimension, so 3 × 3 × 3 = 27 cubic feet."),
                ("How many tons are in a cubic yard?", "It depends on the material density and moisture, so there is no single universal answer."),
                ("Is a cubic yard the same as a truckload?", "No. Truck capacity varies by vehicle, material and supplier."),
            ],
        },
        {
            "slug": "gravel-density-and-tonnage-estimate-guide",
            "title": "Gravel Density and Tonnage Estimate Guide",
            "category": "Landscaping",
            "topic": "landscaping",
            "parent": "gravel",
            "description": "Estimate gravel tons from volume while understanding how density, stone type, moisture and compaction affect the result.",
            "answer": "Gravel tonnage is estimated by multiplying volume by bulk density. Because crushed stone, pea gravel and other aggregates have different densities and moisture conditions, use a supplier's current bulk-density or ton-per-yard figure whenever available.",
            "steps": [
                ("Calculate area and depth", "Measure the planned gravel footprint and installed depth."),
                ("Convert to volume", "Calculate cubic feet and divide by 27 for cubic yards."),
                ("Select density", "Use a material-specific bulk density rather than a generic rock density."),
                ("Review delivery quantity", "Compare the calculated tons with supplier minimums, truck capacity and the desired compaction condition."),
            ],
            "formula": "weight(lb) = volume(ft³) × bulk density(lb/ft³); tons = lb ÷ 2,000",
            "example": "A 100 ft³ gravel layer at an illustrative 105 lb/ft³ bulk density weighs about 10,500 lb, or 5.25 short tons.",
            "mistakes": "Using the density of solid rock instead of bulk aggregate density, ignoring moisture, and treating loose delivery volume as equal to compacted in-place volume.",
            "faqs": [
                ("Why does gravel density vary?", "Particle size distribution, void space, moisture and material type all affect bulk density."),
                ("Should I use the calculator's default density?", "Only as a planning assumption. Supplier data is preferable for purchasing."),
                ("Do I need extra gravel for compaction?", "Potentially. Follow the aggregate supplier or project specification for compaction and loose-to-compacted yield."),
            ],
        },
        {
            "slug": "paint-coverage-and-number-of-coats-guide",
            "title": "Paint Coverage: How Many Coats and Gallons Do You Need?",
            "category": "Paint & Interior",
            "topic": "paint",
            "parent": "paint",
            "description": "Estimate paint gallons from surface area, manufacturer coverage, openings and number of coats without confusing label coverage with guaranteed real-world yield.",
            "answer": "Start with paintable surface area, subtract large openings when appropriate, divide by the manufacturer's stated coverage per gallon and multiply by the number of coats. Actual coverage changes with surface texture, porosity, color change, application method and primer.",
            "steps": [
                ("Measure paintable area", "Calculate wall or ceiling area and subtract significant openings if the estimate calls for it."),
                ("Choose coverage", "Use the current product label or technical data rather than a generic gallons-per-room rule."),
                ("Apply coats", "Multiply the one-coat quantity by the planned number of coats."),
                ("Round for purchase", "Round up to full containers and consider touch-up needs and color matching."),
            ],
            "formula": "gallons = paintable area(ft²) × coats ÷ coverage(ft²/gal)",
            "example": "A 900 ft² paintable surface at 350 ft² per gallon for two coats needs about 900 × 2 ÷ 350 = 5.14 gallons, so a practical purchase may be 6 gallons depending on container sizes and touch-up needs.",
            "mistakes": "Using coverage from a different paint, forgetting the second coat, assuming textured walls cover like smooth drywall, and buying an exact theoretical amount with no touch-up reserve.",
            "faqs": [
                ("Does primer count as a coat?", "Primer is a separate coating step and its coverage should be estimated from the primer's product data."),
                ("Why is my real coverage lower than the label?", "Porosity, texture, application method, color change and surface condition can reduce practical coverage."),
                ("Should I subtract windows?", "Large openings can be subtracted for a more precise estimate; small trim and complex edges may offset some of that savings."),
            ],
        },
        {
            "slug": "roofing-shingle-bundle-and-square-guide",
            "title": "Roofing Shingles: Squares, Bundles and Waste Explained",
            "category": "Roofing",
            "topic": "roofing-decks-fences",
            "parent": "roofing",
            "description": "Understand roofing squares, shingle bundles, roof pitch and waste when estimating asphalt shingles for a simple roof.",
            "answer": "Roofing is commonly quoted in squares, where one square represents 100 square feet of roof area. Calculate the actual sloped roof surface, divide by 100, then convert squares to bundles using the shingle manufacturer's coverage per bundle and add a layout-specific waste allowance.",
            "steps": [
                ("Calculate roof footprint", "Start with the horizontal roof dimensions and account for every roof plane."),
                ("Adjust for pitch", "A pitched roof has more surface area than its horizontal footprint."),
                ("Convert to squares", "Divide total roof surface area by 100."),
                ("Convert to bundles", "Use the current manufacturer's bundle coverage and add waste for hips, valleys, starter courses and cuts as applicable."),
            ],
            "formula": "roofing squares = roof surface area(ft²) ÷ 100",
            "example": "A 2,400 ft² actual roof surface represents 24 roofing squares before accounting for waste and accessory materials.",
            "mistakes": "Using the house footprint as the final roof area, assuming every shingle bundle covers exactly the same area, and forgetting starter, ridge, valley and flashing materials.",
            "faqs": [
                ("How many bundles are in a roofing square?", "It depends on the product. Many products are designed around three bundles per square, but the manufacturer's current coverage controls."),
                ("Does roof pitch change shingle quantity?", "Yes, because pitch changes the actual surface area relative to the horizontal footprint."),
                ("Does a shingle calculator include flashing?", "A shingle quantity estimate should not be assumed to include all roofing accessories; estimate those separately from the roof details."),
            ],
        },
    ]
