from __future__ import annotations

def seo_guides() -> list[dict]:
    return [
        {
            "slug": "how-many-bags-of-concrete-do-i-need",
            "title": "How Many Bags of Concrete Do I Need?",
            "category": "Concrete & Masonry", "topic": "concrete", "parent": "concrete-bag-calculator",
            "description": "Estimate complete bags of premixed concrete from slab volume, bag yield and a visible project allowance.",
            "answer": "Calculate the project volume first, then divide by the exact yield printed on the selected concrete bag. Round up to complete bags and keep the allowance separate.",
            "steps": [("Measure the pour.", "Use length, width and thickness."), ("Calculate volume.", "Convert dimensions to cubic feet."), ("Read bag yield.", "Use the exact product label."), ("Divide and round.", "Round up and confirm the mix instructions.")],
            "formula": "bags = ceil(total volume ÷ yield per bag)",
            "example": "If a small pour needs 12.4 ft³ and each bag yields 0.6 ft³, the planning quantity is 21 bags before any additional allowance.",
            "mistakes": "Do not assume every 60 lb or 80 lb bag has the same yield. Weight and yield vary by product.",
            "faqs": [("Should I buy extra bags?", "A small allowance may help with spillage and uneven forms, but follow product and site guidance."), ("Can I mix different brands?", "Follow the product instructions and avoid mixing systems without confirming compatibility."), ("Is bag concrete suitable for every pour?", "Larger pours may be better served by ready-mix delivery.")],
        },
        {
            "slug": "how-many-tiles-do-i-need",
            "title": "How Many Tiles Do I Need?",
            "category": "Flooring & Tile", "topic": "flooring", "parent": "tile-calculator",
            "description": "Convert tiled surface area into individual tile count, waste allowance and full-box quantities.",
            "answer": "Calculate the net tiled area, divide by the coverage area of one tile, add a layout-specific allowance and round to whole tiles or boxes.",
            "steps": [("Measure the surface.", "Calculate floor, wall or backsplash area."), ("Find tile coverage.", "Convert tile dimensions to square feet."), ("Add waste.", "Consider cuts, pattern and breakage."), ("Round packages.", "Use exact box coverage and round up.")],
            "formula": "tiles = ceil((net area × waste factor) ÷ tile area)",
            "example": "A 100 ft² area using 12 × 12 in tiles with 10% allowance needs about 1,100 tiles before box rounding.",
            "mistakes": "Do not confuse nominal tile size with the actual coverage when spacers, grout joints or mosaics are involved.",
            "faqs": [("Should I keep spare tiles?", "Keeping matching spare material can help future repairs, especially for discontinued products."), ("Does diagonal layout need more?", "Usually, because perimeter cuts create more offcuts."), ("Do wall tiles use the same waste?", "Not always. Surface shape and pattern determine the allowance.")],
        },
        {
            "slug": "how-many-bags-of-gravel-do-i-need",
            "title": "How Many Bags of Gravel Do I Need?",
            "category": "Landscaping", "topic": "landscaping", "parent": "gravel",
            "description": "Convert landscape area and gravel depth into cubic feet, cubic yards and complete bags.",
            "answer": "Multiply area by installed depth in feet to get cubic feet, then divide by the exact volume printed on one bag and round up.",
            "steps": [("Measure the area.", "Split irregular beds into simple shapes."), ("Choose depth.", "Use project-specific aggregate guidance."), ("Calculate volume.", "Area × depth in feet."), ("Convert to bags.", "Divide by the bag's cubic-foot volume.")],
            "formula": "bags = ceil((area × depth) ÷ bag volume)",
            "example": "A 100 ft² bed at 2 in depth equals 16.7 ft³. With 0.5 ft³ per bag, plan for 34 bags before site allowance.",
            "mistakes": "Do not estimate bags from weight alone; bag volume and aggregate density vary.",
            "faqs": [("Is gravel sold by weight or volume?", "Bulk gravel is commonly sold by weight or cubic yard, while retail bags show volume or weight."), ("Does depth include a base?", "Measure and calculate the installed gravel layer separately from any base course."), ("Can I use this for decorative stone?", "Yes for geometric volume, but product density and bag size still vary.")],
        },
        {
            "slug": "how-many-fence-posts-do-i-need",
            "title": "How Many Fence Posts Do I Need?",
            "category": "Roofing, Decks & Fences", "topic": "roofing-decks-fences", "parent": "fence",
            "description": "Estimate fence posts from total run, maximum spacing, corners, ends and gates.",
            "answer": "Divide each straight fence run by the selected maximum section spacing and round up. Then add posts required for ends, corners, gates and transitions.",
            "steps": [("Measure each run.", "Do not combine separate fence lines blindly."), ("Choose spacing.", "Follow the fence system and local requirements."), ("Round sections up.", "A partial section still needs support."), ("Add special posts.", "Count corners, ends and gate supports separately.")],
            "formula": "straight-run sections = ceil(run length ÷ maximum spacing)",
            "example": "A 64 ft straight run at 8 ft spacing needs 8 sections; ends and any gate or corner posts are added separately.",
            "mistakes": "Do not assume a straight-run count includes gate hardware, corners or terminal posts.",
            "faqs": [("How far apart should posts be?", "Spacing depends on fence height, material, wind, soil and system instructions."), ("Are gate posts different?", "Gate posts often need additional support and hardware-specific sizing."), ("Should posts be evenly spaced?", "Even spacing is useful, but site boundaries and gate locations may require adjustments.")],
        },
        {
            "slug": "how-to-budget-a-bathroom-remodel",
            "title": "How to Build a Bathroom Remodel Budget",
            "category": "Renovation & Remodeling", "topic": "flooring", "parent": "bathroom-remodel-cost-calculator",
            "description": "Create an early bathroom remodel budget by separating fixtures, surfaces, plumbing, labor and contingency.",
            "answer": "Start with room size and project scope, then price fixtures, tile, vanity, flooring, plumbing, electrical, labor and permits as separate components.",
            "steps": [("Define the scope.", "Cosmetic updates and layout changes are different projects."), ("List materials.", "Separate fixtures, tile, vanity, glass and accessories."), ("Estimate labor.", "Include demolition, installation and trade work."), ("Add site costs.", "Account for permits, disposal and an uncertainty allowance.")],
            "formula": "early budget = materials + demolition + labor + permits + site allowance",
            "example": "A useful early budget shows separate fixture, surface and labor ranges instead of multiplying room size by one unexplained rate.",
            "mistakes": "Do not treat an online average as a local quote, especially when plumbing moves or hidden damage may be involved.",
            "faqs": [("Does a bathroom remodel need permits?", "Requirements vary by location and scope; check local authorities."), ("Should plumbing be a separate line?", "Yes. Moving supply or drain lines can materially change cost."), ("How much contingency is needed?", "The appropriate allowance depends on project age, access, scope and unknown conditions.")],
        },
    ]
