from __future__ import annotations

def seo_guides() -> list[dict]:
    pages = [
        ("concrete-slab-thickness-guide","Concrete Slab Thickness Guide","Concrete & Masonry","concrete","concrete-slab-calculator","Choose a planning thickness only after considering use, soil, reinforcement and local requirements.","Concrete thickness is project-specific. Use the calculator for volume after the slab design, base and reinforcement requirements are established.","Confirm use","A patio, walkway, garage and structural slab have different requirements.","Measure area","Use length and width for the designed slab footprint.","Convert thickness","Change inches to feet before calculating volume.","Confirm design","Check local requirements and qualified project guidance."),
        ("concrete-footing-volume-guide","How to Calculate Concrete for Footings","Concrete & Masonry","concrete","concrete-footing-calculator","Estimate footing concrete from continuous footing length or separate pad dimensions.","Calculate each footing section from its designed length, width and depth, then add the sections before converting to cubic yards.","List sections","Separate strip footings, pads and steps.","Measure dimensions","Use the designed concrete dimensions.","Calculate volumes","Multiply length × width × depth for each section.","Add together","Convert the total to cubic yards and review ordering allowance."),
        ("how-to-calculate-laminate-flooring","How to Calculate Laminate Flooring","Flooring & Tile","flooring","laminate-flooring-calculator","Estimate laminate flooring area, waste and complete boxes from room measurements.","Measure the net floor area, add a layout-specific waste allowance and divide by the exact carton coverage.","Measure rooms","Split irregular rooms into rectangles.","Add areas","Combine rooms using the same laminate SKU.","Apply waste","Consider direction, cuts and transitions.","Round boxes","Use the printed carton coverage and round up."),
        ("bathroom-floor-tile-quantity","How Much Floor Tile for a Bathroom?","Flooring & Tile","flooring","bathroom-tile-calculator","Calculate bathroom floor tile while keeping fixtures, cuts, grout joints and box rounding visible.","Measure the actual tiled floor, add an allowance for cuts and breakage, then round to complete boxes.","Measure tile area","Use finished floor dimensions.","Review exclusions","Subtract only meaningful untiled areas.","Add waste","Complex layouts may need more than a simple room.","Round packages","Use the exact selected tile box coverage."),
        ("paint-ceiling-calculator-guide","How to Calculate Ceiling Paint","Paint & Finishes","paint","ceiling-paint-calculator","Estimate ceiling paint from ceiling area, coats and the product coverage rate.","Multiply ceiling length by width, multiply by coats and divide by the exact coverage shown on the paint label.","Measure ceiling","Use finished ceiling dimensions.","Calculate area","Length × width gives square feet.","Set coats","Primer and finish coats may use different products.","Round cans","Round up to available can sizes."),
        ("exterior-house-paint-guide","How to Estimate Exterior House Paint","Paint & Finishes","paint","exterior-paint-calculator","Plan exterior paint from wall surfaces, openings, stories, coats and product coverage.","Estimate each exterior wall plane, subtract major openings and use the product-specific coverage rate for the planned coats.","List wall planes","Measure each elevation separately.","Subtract openings","Remove large windows and doors.","Apply coats","Include primer or finish coats separately.","Check surface","Siding, masonry and texture change coverage."),
        ("gravel-driveway-volume-guide","How to Calculate Gravel for a Driveway","Landscaping","landscaping","gravel-calculator","Estimate driveway gravel volume from area, layer depth and aggregate type.","Calculate each layer separately because base, sub-base and surface aggregate may use different depths and materials.","Measure area","Split the driveway into simple sections.","Set layer depths","Use the project specification for each layer.","Calculate volume","Area × depth gives cubic feet.","Convert quantity","Use supplier density or cubic-yard rules."),
        ("roofing-underlayment-guide","How Much Roofing Underlayment Do I Need?","Roofing, Decks & Fences","roofing-decks-fences","roofing-material-calculator","Estimate underlayment from roof surface area while accounting for roll coverage and overlap.","Use roof surface area, then divide by the effective roll coverage after overlaps rather than the gross label area alone.","Measure roof planes","Calculate each slope or use safe plan measurements.","Read roll coverage","Check the product's effective coverage and overlap rules.","Add roof details","Valleys, hips and penetrations affect material use.","Round rolls","Purchase complete rolls and follow installation guidance."),
        ("fence-panel-calculator-guide","How Many Fence Panels Do I Need?","Roofing, Decks & Fences","roofing-decks-fences","fence","Estimate fence panels from total run, panel width, posts, gates and end conditions.","Divide each fence run by the actual installed panel width and round up, then account for gates, corners and partial sections.","Measure runs","Separate straight lines and transitions.","Confirm panel width","Use actual installed width, not only nominal size.","Round panels","A partial panel still requires a complete unit or field cut.","Add posts and gates","Panel quantity does not replace post planning."),
        ("bathroom-remodel-material-checklist","Bathroom Remodel Materials Checklist","Renovation & Remodeling","flooring","bathroom-remodel-cost-calculator","Organize bathroom remodel materials before estimating cost for fixtures, surfaces, plumbing and installation.","A reliable early estimate lists demolition, substrate, waterproofing, tile, fixtures, cabinetry, plumbing, electrical and labor separately.","Define scope","Cosmetic updates and layout changes differ.","List surfaces","Include floor, walls, shower and backsplash.","List systems","Track plumbing, electrical, ventilation and waterproofing.","Price separately","Use local supplier and trade estimates."),
    ]
    result = []
    for slug, title, category, topic, parent, description, answer, s1, d1, s2, d2, s3, d3, s4, d4 in pages:
        result.append({
            "slug": slug, "title": title, "category": category, "topic": topic, "parent": parent,
            "description": description, "answer": answer,
            "steps": [(s1,d1),(s2,d2),(s3,d3),(s4,d4)],
            "formula": "planning quantity = measured project area or volume × project-specific factor",
            "example": "Use the measured project dimensions, apply the product or layout assumptions, then round to the package or supplier unit.",
            "mistakes": "Do not hide waste, package coverage, product yield or site assumptions inside one unexplained number.",
            "faqs": [("Is this a final quote?", "No. It is an early planning estimate and should be checked against product specifications and local conditions."), ("Why do products differ?", "Coverage, package size, installation method and material properties vary by product."), ("Should I confirm with a professional?", "Yes when the work affects structure, waterproofing, roofing safety, utilities or code compliance.")],
        })
    return result
