from __future__ import annotations


def seo_guides() -> list[dict]:
    return [
        {
            "slug": "how-to-calculate-concrete-yards",
            "title": "How to Calculate Concrete Yards",
            "category": "Concrete & Masonry",
            "topic": "concrete",
            "parent": "concrete",
            "description": "Learn the simple cubic-yard formula for concrete slabs, pads, patios and similar rectangular pours.",
            "answer": "Multiply length by width by thickness to get cubic feet, then divide by 27 to convert cubic feet to cubic yards. Convert thickness from inches to feet before multiplying.",
            "steps": [("Measure length and width.", "Use feet for both dimensions."), ("Convert thickness to feet.", "Divide inches by 12."), ("Find cubic feet.", "Multiply length × width × thickness in feet."), ("Convert to cubic yards.", "Divide cubic feet by 27, then add a project allowance before ordering.")],
            "formula": "cubic yards = length(ft) × width(ft) × thickness(ft) ÷ 27",
            "example": "A 12 ft × 10 ft slab at 4 in thick is 12 × 10 × 0.333 ÷ 27 ≈ 1.48 yd³ before any waste allowance.",
            "mistakes": "The most common errors are leaving thickness in inches, forgetting to divide by 27, and ordering the exact geometric amount with no allowance for site variation or spillage.",
            "faqs": [("Why divide by 27?", "One cubic yard contains 27 cubic feet."), ("Should I round concrete up?", "Concrete is normally ordered with a project-specific allowance rather than to the exact geometric decimal."), ("Can I use this for irregular shapes?", "Split the project into simple measurable sections, calculate each section, then add them together.")],
        },
        {
            "slug": "concrete-waste-allowance-guide",
            "title": "How Much Extra Concrete Should You Order?",
            "category": "Concrete & Masonry",
            "topic": "concrete",
            "parent": "concrete",
            "description": "Understand why concrete orders often include extra material and how to keep the allowance separate from the measured volume.",
            "answer": "There is no universal waste percentage for every pour. A modest planning allowance may cover uneven subgrade, forms, spillage and measurement uncertainty, but the right amount depends on the project and supplier guidance.",
            "steps": [("Calculate raw volume.", "Use actual measured dimensions first."), ("Review uncertainty.", "Consider subgrade variation, form accuracy and access."), ("Choose an allowance.", "Keep the percentage visible rather than hiding it inside dimensions."), ("Confirm the order.", "Check with the ready-mix supplier or installer before purchase.")],
            "formula": "order volume = measured volume × (1 + allowance rate)",
            "example": "If measured volume is 2.00 yd³ and you choose a 7% planning allowance, the planning quantity becomes 2.14 yd³ before supplier order increments.",
            "mistakes": "Do not inflate every dimension and also add a percentage, because that can double-count the allowance. Keep measured geometry and extra material as separate steps.",
            "faqs": [("Is 10% always required?", "No. Ten percent is only a common rule of thumb in some DIY discussions, not a universal requirement."), ("What if the ground is uneven?", "Uneven excavation can materially increase volume, so re-measure depth and confirm field conditions before ordering."), ("Does a concrete truck sell exact decimals?", "Minimum orders, short-load fees and supplier increments vary, so verify the actual ordering rules locally.")],
        },
        {
            "slug": "how-to-measure-room-for-flooring",
            "title": "How to Measure a Room for Flooring",
            "category": "Flooring & Tile",
            "topic": "flooring",
            "parent": "flooring",
            "description": "Measure room square footage correctly before adding flooring waste and rounding to full boxes.",
            "answer": "For a rectangular room, multiply length by width. For L-shaped or irregular rooms, split the floor into rectangles, calculate each area separately and add the results.",
            "steps": [("Sketch the room.", "Mark closets, alcoves and unusual shapes."), ("Measure each section.", "Use the same unit for every dimension."), ("Calculate area.", "Multiply length × width for each rectangle."), ("Add sections.", "Combine the measured areas before applying waste and box rounding.")],
            "formula": "room area = sum of each rectangular section's length × width",
            "example": "A 12 × 10 ft room plus a 3 × 4 ft closet is 120 + 12 = 132 ft² before waste.",
            "mistakes": "Common errors include forgetting closets, measuring wall-to-wall in mixed units, and rounding each small section separately instead of totaling the measured area first.",
            "faqs": [("Do I include closets?", "Include closets when they will receive the same flooring."), ("Should I subtract cabinets?", "Only subtract fixed areas that definitely will not receive flooring."), ("When do I add waste?", "Add waste after calculating the total measured floor area and before box rounding.")],
        },
        {
            "slug": "flooring-waste-percentage-guide",
            "title": "Flooring Waste Percentage Guide",
            "category": "Flooring & Tile",
            "topic": "flooring",
            "parent": "flooring",
            "description": "Learn what drives flooring waste and why simple rooms, diagonal layouts and patterned installs need different allowances.",
            "answer": "A straightforward rectangular installation often uses a modest waste allowance, while diagonal layouts, many cuts, pattern matching and complex room shapes can need more. Use the product and installer guidance for the actual project.",
            "steps": [("Measure net area.", "Calculate the real floor footprint first."), ("Assess layout complexity.", "Count angled walls, niches, transitions and pattern requirements."), ("Set waste separately.", "Apply a visible percentage to measured area."), ("Round to packages.", "After waste, convert the quantity to complete boxes.")],
            "formula": "purchase area = measured area × (1 + waste rate)",
            "example": "A 200 ft² room with 10% waste becomes 220 ft² before dividing by the box coverage.",
            "mistakes": "Do not use package rounding as a substitute for waste. A box may create some extra material, but the amount is accidental and may not cover layout-related cuts.",
            "faqs": [("Is 10% flooring waste enough?", "It can be a reasonable planning starting point for simple layouts, but it is not guaranteed for every product or pattern."), ("Does diagonal flooring need more?", "Usually yes because diagonal cuts create more offcuts at the room perimeter."), ("Should I keep spare boards?", "Some homeowners keep matching material for future repairs, but that is separate from installation waste.")],
        },
        {
            "slug": "how-many-flooring-boxes-do-i-need",
            "title": "How Many Boxes of Flooring Do I Need?",
            "category": "Flooring & Tile",
            "topic": "flooring",
            "parent": "flooring",
            "description": "Convert project square footage into full flooring boxes using the exact coverage printed on the carton.",
            "answer": "Add your chosen waste allowance to the measured floor area, divide by the square feet covered by one box, then round up to the next whole box.",
            "steps": [("Measure the floor.", "Find total square footage."), ("Add waste.", "Apply the project-specific allowance."), ("Read box coverage.", "Use the exact square-foot coverage on the carton."), ("Divide and round up.", "Flooring is usually purchased in complete boxes.")],
            "formula": "boxes = ceil((measured area × waste factor) ÷ box coverage)",
            "example": "A project needing 215 ft² after waste with 23.5 ft² per box requires 9.15 boxes, so the purchase quantity is 10 boxes.",
            "mistakes": "Do not round the project area down, and do not assume every brand or SKU covers the same square footage per carton.",
            "faqs": [("Why must boxes round up?", "Most flooring products are sold only in complete cartons."), ("Can I use online box coverage?", "Use the current coverage for the exact SKU you are buying, preferably from the package or manufacturer."), ("What if I have unopened boxes left?", "Return policies vary by retailer, so check them before relying on returns.")],
        },
        {
            "slug": "how-to-measure-backsplash-for-tile",
            "title": "How to Measure a Backsplash for Tile",
            "category": "Flooring & Tile",
            "topic": "flooring",
            "parent": "tile",
            "description": "Measure backsplash square footage, handle multiple wall sections and plan for tile cuts around outlets and edges.",
            "answer": "Measure each backsplash section as width × height, convert inches to feet when needed, add the sections, then apply a waste allowance before box rounding.",
            "steps": [("Split the backsplash into rectangles.", "Treat separate wall runs as separate sections."), ("Measure width and height.", "Keep units consistent."), ("Add section areas.", "Sum the tiled surfaces."), ("Apply waste and package rounding.", "Use the actual tile box coverage.")],
            "formula": "backsplash area = sum of section width × section height",
            "example": "A 15 ft backsplash that is 18 in high covers 15 × 1.5 = 22.5 ft² before waste.",
            "mistakes": "Small outlet openings do not necessarily reduce the order much because they also create cuts and breakage. Avoid over-subtracting small penetrations.",
            "faqs": [("Do I subtract outlets?", "Usually not for a basic planning estimate because the saved area is small and extra cutting is required."), ("How much waste for backsplash tile?", "Simple layouts may use a modest allowance, while mosaics, patterns and many cuts may require more."), ("Should I measure behind appliances?", "Include only surfaces you actually plan to tile.")],
        },
        {
            "slug": "tile-waste-percentage-guide",
            "title": "Tile Waste Percentage Guide",
            "category": "Flooring & Tile",
            "topic": "flooring",
            "parent": "tile",
            "description": "Understand tile waste for straight, diagonal and patterned layouts before rounding to full boxes.",
            "answer": "Tile waste depends on layout, room shape, tile size, pattern matching and breakage risk. Straight rectangular layouts generally need less extra material than diagonal or highly patterned installations.",
            "steps": [("Calculate net tiled area.", "Measure floors or walls first."), ("Review the pattern.", "Diagonal and centered patterns can create more offcuts."), ("Apply a waste allowance.", "Keep it visible and separate from package rounding."), ("Round to boxes.", "Use actual box coverage for the final purchase quantity.")],
            "formula": "purchase area = tiled area × (1 + waste rate)",
            "example": "A 100 ft² tiled area with a 12% planning allowance becomes 112 ft² before full-box rounding.",
            "mistakes": "Avoid assuming that leftover square footage inside the final box always equals enough waste. Pattern layout can make spare pieces unusable in specific locations.",
            "faqs": [("Is 10% tile waste standard?", "It is a common planning rule for simple projects, but actual requirements vary."), ("Does large-format tile need more?", "Large tiles can create significant offcuts when room dimensions do not align with tile dimensions."), ("What about special-order tile?", "For products with long lead times or shade variation, discuss spare material with the supplier or installer.")],
        },
        {
            "slug": "how-to-measure-walls-for-paint",
            "title": "How to Measure Walls for Paint",
            "category": "Paint & Finishes",
            "topic": "paint",
            "parent": "paint",
            "description": "Calculate paintable wall area from room perimeter, wall height, openings and coat count.",
            "answer": "For a rectangular room, multiply the room perimeter by wall height to get gross wall area. Subtract meaningful doors and windows if desired, then multiply by the number of coats.",
            "steps": [("Find perimeter.", "Add all wall lengths around the room."), ("Multiply by height.", "This gives gross wall area."), ("Subtract large openings.", "Doors and windows can be removed for a tighter estimate."), ("Apply coats and coverage.", "Use the actual paint coverage rate.")],
            "formula": "paintable wall area = perimeter × wall height − openings",
            "example": "A 12 × 10 ft room has a 44 ft perimeter. At 8 ft high, gross wall area is 352 ft² before openings.",
            "mistakes": "Do not use floor square footage as wall area. Wall area depends on perimeter and height, so two rooms with the same floor area can need different amounts of paint.",
            "faqs": [("Should I subtract every window?", "You can subtract meaningful openings, but very small openings may be offset by cutting-in and touch-up needs."), ("Do I include closets?", "Include closet walls when they will receive the same paint."), ("What about ceilings?", "Estimate ceilings separately because their area and paint product may differ.")],
        },
        {
            "slug": "paint-coverage-per-gallon-guide",
            "title": "Paint Coverage per Gallon: What to Use",
            "category": "Paint & Finishes",
            "topic": "paint",
            "parent": "paint",
            "description": "Learn why paint coverage varies and why the exact product label is better than a generic square-feet-per-gallon assumption.",
            "answer": "Coverage varies by paint, substrate, texture, porosity, color change and application method. Use the manufacturer’s coverage range for the exact product, then plan conservatively for rough or porous surfaces.",
            "steps": [("Choose the actual paint.", "Find the product coverage specification."), ("Inspect the surface.", "Rough or porous surfaces can reduce coverage."), ("Set coat count.", "Primer and finish coats should be planned separately when products differ."), ("Calculate and round.", "Divide total coverage area by product coverage and round to available can sizes.")],
            "formula": "gallons = total coat-area ÷ product coverage per gallon",
            "example": "If two coats create 700 coverage ft² and the paint is rated at 350 ft²/gal, the theoretical need is 2 gallons before real-world allowance and can-size rounding.",
            "mistakes": "Do not assume every paint covers 400 ft² per gallon. Product specifications and surface conditions can materially change the result.",
            "faqs": [("Why does textured wall use more paint?", "Texture increases surface area and can hold more coating in recesses."), ("Does primer count as paint coverage?", "Primer should usually be estimated using its own coverage rate because it is a different product."), ("Can color change affect coats?", "Yes. Strong color changes can require primer or additional finish coats depending on the paint system.")],
        },
        {
            "slug": "how-to-calculate-cubic-yards",
            "title": "How to Calculate Cubic Yards for Landscaping",
            "category": "Landscaping",
            "topic": "landscaping",
            "parent": "gravel",
            "description": "Convert landscape bed length, width and depth into cubic yards for gravel, mulch, soil and similar bulk materials.",
            "answer": "Multiply length × width × depth in feet to get cubic feet, then divide by 27 for cubic yards. Convert depth from inches to feet before multiplying.",
            "steps": [("Measure length and width.", "Use feet."), ("Convert depth to feet.", "Divide inches by 12."), ("Calculate cubic feet.", "Multiply length × width × depth."), ("Convert to cubic yards.", "Divide by 27 and apply any project allowance.")],
            "formula": "cubic yards = length(ft) × width(ft) × depth(ft) ÷ 27",
            "example": "A 20 × 10 ft bed at 3 in deep is 20 × 10 × 0.25 ÷ 27 ≈ 1.85 yd³.",
            "mistakes": "The most common mistake is multiplying by depth in inches without converting to feet first.",
            "faqs": [("Is a cubic yard always 27 cubic feet?", "Yes, by unit conversion."), ("Can I use this for mulch and gravel?", "Yes for geometric volume, but weight and compaction differ by material."), ("Should I add extra material?", "A project allowance may be useful for settlement, grading and measurement uncertainty, depending on the material and job.")],
        },
        {
            "slug": "gravel-depth-guide",
            "title": "Gravel Depth Guide for Common DIY Projects",
            "category": "Landscaping",
            "topic": "landscaping",
            "parent": "gravel",
            "description": "Understand why gravel depth depends on use, base conditions and aggregate type before calculating volume or weight.",
            "answer": "There is no single gravel depth for every project. Decorative beds, walkways, drainage layers and driveways have different performance needs, and structural or drainage applications should follow project-specific guidance.",
            "steps": [("Identify the use.", "Decorative cover and load-bearing bases are different jobs."), ("Check the subgrade and base.", "Existing conditions affect required build-up."), ("Choose the specified depth.", "Use contractor, manufacturer or project guidance."), ("Calculate volume.", "Use the chosen installed depth in the gravel calculator.")],
            "formula": "volume = area × installed depth",
            "example": "A 100 ft² decorative bed at 2 in deep uses 100 × 0.167 ≈ 16.7 ft³ before any allowance.",
            "mistakes": "Do not borrow a driveway depth for a decorative bed or vice versa. Compaction, drainage and load requirements change the specification.",
            "faqs": [("Does gravel compact?", "Many aggregates settle or compact, so delivered and installed volume may differ."), ("Is pea gravel good for driveways?", "Material suitability depends on the project design and local conditions; use appropriate aggregate guidance."), ("Do I need landscape fabric?", "That depends on the project goals, soil conditions and installation method.")],
        },
        {
            "slug": "mulch-depth-guide",
            "title": "How Deep Should Mulch Be?",
            "category": "Landscaping",
            "topic": "landscaping",
            "parent": "mulch",
            "description": "Choose a mulch depth for planning and convert that depth into cubic yards or bags without over-applying around plants.",
            "answer": "Mulch depth depends on material, existing mulch and landscape conditions. Use horticultural guidance appropriate to the plantings and keep mulch away from direct contact with trunks and stems.",
            "steps": [("Measure the bed area.", "Split irregular beds into simple sections."), ("Check existing mulch.", "Do not automatically add a full new layer every year."), ("Choose the target depth.", "Follow suitable horticultural guidance."), ("Calculate volume.", "Convert the chosen depth into cubic yards or bags.")],
            "formula": "mulch volume = bed area × installed depth",
            "example": "A 200 ft² bed at 3 in deep is 200 × 0.25 = 50 ft³, or about 1.85 yd³ before bag or bulk rounding.",
            "mistakes": "Avoid piling mulch against tree trunks or plant stems and avoid ignoring the depth of existing material already in the bed.",
            "faqs": [("Can mulch be too deep?", "Yes. Excessive mulch can create moisture and root-zone problems depending on the planting."), ("Should old mulch be removed?", "Not always. Evaluate the existing layer and landscape conditions before adding more."), ("How many bags make a yard?", "It depends on the bag volume. Divide 27 cubic feet by the cubic-foot volume printed on one bag.")],
        },
        {
            "slug": "how-to-measure-roof-area",
            "title": "How to Estimate Roof Area from a Simple Gable Roof",
            "category": "Roofing, Decks & Fences",
            "topic": "roofing-decks-fences",
            "parent": "roofing",
            "description": "Understand the footprint-and-slope approach used for early roof-area planning on a simple gable roof.",
            "answer": "For a simple gable roof, start with the horizontal building footprint and multiply by an appropriate slope factor. Complex roofs with hips, valleys, dormers and multiple pitches should be measured section by section.",
            "steps": [("Measure the footprint.", "Use horizontal plan dimensions."), ("Identify roof pitch.", "Pitch determines the slope factor."), ("Apply the factor.", "Multiply plan area by slope factor for an approximate roof surface area."), ("Add project-specific waste.", "Roof geometry and shingle layout affect the final order.")],
            "formula": "roof surface area ≈ horizontal footprint × slope factor",
            "example": "A 30 × 40 ft footprint is 1,200 ft². If the appropriate slope factor were 1.118, estimated roof surface area would be about 1,342 ft² before waste.",
            "mistakes": "Do not use this simplified method for complicated roofs without breaking them into separate roof planes. Do not work on a roof merely to obtain measurements if access is unsafe.",
            "faqs": [("What is a roofing square?", "One roofing square equals 100 ft² of roof area."), ("Does pitch increase roof area?", "Yes. A steeper slope has more surface area than the same horizontal footprint."), ("Can I measure from the ground?", "Some planning measurements can be derived from plans or safe ground measurements, but complex roofs often require professional measurement methods.")],
        },
        {
            "slug": "roof-pitch-factor-guide",
            "title": "Roof Pitch Factor Guide",
            "category": "Roofing, Decks & Fences",
            "topic": "roofing-decks-fences",
            "parent": "roofing",
            "description": "Learn what a roof pitch factor represents and why it converts horizontal plan area into sloped roof surface area.",
            "answer": "A pitch factor is the ratio between the sloped roof surface length and its horizontal run. It can be derived from the roof rise and run using the Pythagorean theorem.",
            "steps": [("Identify rise and run.", "Roof pitch is often expressed as rise per 12 inches of run."), ("Calculate slope length ratio.", "Use the square root of run² + rise² divided by run."), ("Multiply plan area.", "Apply the factor to the horizontal roof footprint."), ("Treat separate pitches separately.", "Mixed-pitch roofs need separate calculations.")],
            "formula": "pitch factor = √(run² + rise²) ÷ run",
            "example": "For a 6:12 pitch, factor = √(12² + 6²) ÷ 12 ≈ 1.118.",
            "mistakes": "Do not confuse pitch factor with waste factor. Pitch changes geometric surface area; waste covers cutting, layout and project allowance.",
            "faqs": [("Is 6:12 the same as 50% slope?", "A 6:12 pitch has a rise equal to half the run, which corresponds to 50% grade, but the roof surface factor is a different value."), ("Does every roof plane use one factor?", "Only if every plane has the same pitch."), ("Can I skip pitch for a flat roof?", "Low-slope and flat roofing systems have different design and material considerations; use the appropriate project method.")],
        },
        {
            "slug": "fence-post-spacing-guide",
            "title": "Fence Post Spacing: How to Plan Sections",
            "category": "Roofing, Decks & Fences",
            "topic": "roofing-decks-fences",
            "parent": "fence",
            "description": "Turn total fence run into planning sections while keeping maximum spacing, corners and gates visible as separate decisions.",
            "answer": "For early quantity planning, divide total run by the chosen maximum section spacing and round up to whole sections. Posts are then related to the section count, with extra posts often needed for gates, corners and layout changes.",
            "steps": [("Measure total run.", "Break separate fence lines into sections."), ("Choose maximum spacing.", "Use the fence system or project specification."), ("Round section count up.", "A partial section still needs support."), ("Add special locations.", "Account for corners, gates, ends and transitions separately.")],
            "formula": "sections = ceil(total run ÷ maximum section spacing)",
            "example": "A 73 ft straight run with an 8 ft maximum planning spacing needs ceil(73 ÷ 8) = 10 sections before gate or corner adjustments.",
            "mistakes": "Do not treat a generic spacing rule as a structural design. Wind, fence height, material, soil, post size and local requirements can change actual spacing.",
            "faqs": [("Is 8 ft spacing always correct?", "No. It is common in some fence systems but not universal."), ("Do gates need extra posts?", "Gates commonly need dedicated support posts or hardware-specific framing."), ("What about corners?", "Corners and direction changes should be counted explicitly rather than hidden in a straight-run formula.")],
        },
        {
            "slug": "deck-board-spacing-guide",
            "title": "Deck Board Spacing and Quantity Planning",
            "category": "Roofing, Decks & Fences",
            "topic": "roofing-decks-fences",
            "parent": "deck",
            "description": "Understand how board face width and gap affect deck-board rows and total linear-foot planning.",
            "answer": "Board rows depend on the installed board face width plus the planned gap. The correct gap depends on board material, moisture condition and manufacturer installation instructions.",
            "steps": [("Confirm installed board width.", "Use actual face width, not only nominal lumber size."), ("Choose the required gap.", "Follow the board manufacturer or project specification."), ("Calculate row module.", "Add board width and gap."), ("Estimate rows and linear feet.", "Round rows up, then multiply by board run length and add waste separately.")],
            "formula": "rows ≈ deck width ÷ (board face width + gap)",
            "example": "If the deck width is 12 ft (144 in) and each installed module is 5.625 in, the raw row count is about 25.6, so planning requires 26 rows.",
            "mistakes": "Do not assume every 5/4 or composite board has the same actual face width, and do not choose a gap without checking material-specific installation instructions.",
            "faqs": [("Do composite boards need gaps?", "Yes, but the required spacing depends on the specific manufacturer and temperature conditions."), ("Should I include board overhang?", "Include the intended finished dimensions and trimming method in your layout plan."), ("Does this calculate joists?", "No. Joist layout is a separate structural design and code-compliance task.")],
        },
    ]
