from __future__ import annotations

def seo_guides() -> list[dict]:
    return [
        {
            "slug": "how-to-calculate-paint-for-a-room",
            "title": "How Much Paint Do I Need for a Room?",
            "category": "Paint & Finishes", "topic": "paint", "parent": "paint",
            "description": "Estimate room paint from wall perimeter, height, openings, coverage and number of coats.",
            "answer": "Calculate gross wall area from room perimeter multiplied by wall height, subtract major openings, multiply by coats and divide by the product coverage rate.",
            "steps": [("Measure the room.", "Add wall lengths to find perimeter."), ("Calculate wall area.", "Multiply perimeter by wall height."), ("Subtract openings.", "Remove large doors and windows when useful."), ("Apply coats and coverage.", "Round to the available can size.")],
            "formula": "gallons = (wall area × coats) ÷ coverage per gallon",
            "example": "A room with 352 ft² of gross wall area, 30 ft² of openings and two coats has 644 ft² of coat-area before dividing by product coverage.",
            "mistakes": "Do not use floor area as wall area, and do not assume every paint product has the same coverage.",
            "faqs": [("Should I include the ceiling?", "Estimate the ceiling separately."), ("Do dark colors need more paint?", "They may require additional coats or primer depending on the existing color and product."), ("Should I buy extra?", "Keep a small amount for touch-ups, but follow the retailer's return policy for unopened cans.")],
        },
        {
            "slug": "how-to-calculate-vinyl-flooring",
            "title": "How to Calculate Vinyl Flooring",
            "category": "Flooring & Tile", "topic": "flooring", "parent": "flooring",
            "description": "Convert room measurements into vinyl flooring square footage, waste and package quantities.",
            "answer": "Measure the total floor area, add a layout-specific waste allowance, then divide by the coverage of the selected vinyl product or box.",
            "steps": [("Measure each room.", "Split irregular rooms into rectangles."), ("Add the areas.", "Combine only surfaces using the same product."), ("Apply waste.", "Consider seams, cuts, direction and room shape."), ("Round packages.", "Use the exact carton or roll coverage.")],
            "formula": "purchase area = measured area × (1 + waste rate)",
            "example": "A 450 ft² project with 8% planning waste requires 486 ft² before package rounding.",
            "mistakes": "Do not mix click-lock, glue-down and sheet-vinyl coverage assumptions; each product has different installation and package rules.",
            "faqs": [("Does sheet vinyl use boxes?", "No. Sheet products may be priced by roll or cut length and need seam planning."), ("Should closets be included?", "Include them if they receive the same flooring."), ("Can I install over every floor?", "Subfloor condition and product requirements must be checked before installation.")],
        },
        {
            "slug": "how-to-calculate-mulch-bags",
            "title": "How Many Bags of Mulch Do I Need?",
            "category": "Landscaping", "topic": "landscaping", "parent": "mulch",
            "description": "Convert landscape bed area and mulch depth into cubic feet, cubic yards and complete bags.",
            "answer": "Multiply bed area by the planned depth in feet, then divide total cubic feet by the cubic-foot volume printed on one bag and round up.",
            "steps": [("Measure bed area.", "Break irregular beds into rectangles or simple shapes."), ("Choose depth.", "Check existing mulch before adding a new layer."), ("Calculate cubic feet.", "Multiply area by depth in feet."), ("Divide by bag volume.", "Round up to full bags.")],
            "formula": "bags = ceil((area × depth in feet) ÷ bag volume)",
            "example": "A 120 ft² bed at 3 in deep is 30 ft³. With 2 ft³ per bag, the planning quantity is 15 bags.",
            "mistakes": "Do not assume every bag is 2 cubic feet. Read the exact package volume.",
            "faqs": [("How many bags are in a cubic yard?", "Divide 27 cubic feet by the bag's cubic-foot volume."), ("Should mulch touch tree trunks?", "Keep mulch away from direct contact with trunks and stems."), ("Does mulch settle?", "Some materials settle, so supplier guidance and actual site conditions matter.")],
        },
        {
            "slug": "how-to-calculate-asphalt-driveway",
            "title": "How to Calculate Asphalt for a Driveway",
            "category": "Concrete & Masonry", "topic": "concrete", "parent": "asphalt-calculator",
            "description": "Estimate asphalt driveway volume and weight from area, thickness and material density.",
            "answer": "Calculate area, multiply by compacted thickness to find volume, then multiply by the appropriate asphalt density to estimate weight. Supplier and paving specifications control the final order.",
            "steps": [("Measure the paved area.", "Split irregular driveways into simple sections."), ("Choose design thickness.", "Use project and base-condition guidance."), ("Calculate volume.", "Area × thickness gives cubic feet or cubic yards."), ("Convert to weight.", "Use the supplier's density or tonnage factor.")],
            "formula": "weight = area × thickness × material density",
            "example": "A 1,000 ft² area at 2 in compacted thickness has 166.7 ft³ of compacted volume before density conversion.",
            "mistakes": "Do not treat loose delivery volume as the same as compacted pavement volume, and do not choose thickness without considering base and traffic.",
            "faqs": [("Is asphalt sold by cubic yard?", "Many suppliers price or deliver asphalt by weight, commonly tons."), ("Does compaction matter?", "Yes. Compacted thickness and delivered material volume are not identical."), ("Can this replace a paving estimate?", "No. It is an early planning estimate only.")],
        },
        {
            "slug": "how-to-calculate-bricks-for-a-wall",
            "title": "How Many Bricks Do I Need for a Wall?",
            "category": "Concrete & Masonry", "topic": "concrete", "parent": "brick-calculator",
            "description": "Estimate brick quantities from wall dimensions, brick face size, mortar joints and project waste.",
            "answer": "Calculate the wall area, divide by the coverage area of one brick including its planned mortar joint, subtract meaningful openings and round up with a visible allowance.",
            "steps": [("Measure the wall.", "Use length and height."), ("Subtract openings.", "Remove large doors and windows."), ("Use actual brick module.", "Include brick face dimensions and mortar joint."), ("Round the purchase.", "Add a project-specific breakage and cutting allowance.")],
            "formula": "bricks ≈ net wall area ÷ brick module area",
            "example": "A 200 ft² net wall divided by a 0.071 ft² brick module needs about 2,817 bricks before allowance and bond-specific adjustments.",
            "mistakes": "Do not calculate from brick size alone without considering the mortar joint and bond pattern.",
            "faqs": [("Do all bricks cover the same area?", "No. Brick dimensions and mortar joints vary."), ("Should openings be subtracted?", "Large openings should generally be subtracted; small cuts may still create waste."), ("Is this a structural design?", "No. Wall support, ties, footing and code requirements need qualified design.")],
        },
    ]
