from __future__ import annotations

def seo_guides() -> list[dict]:
    return [
        {
            "slug": "pipe-flow-rate-and-pressure-loss-guide",
            "title": "Pipe Flow Rate and Pressure Loss Guide",
            "category": "Plumbing Planning",
            "topic": "plumbing",
            "parent": "pipe-flow-calculator",
            "description": "Understand how pipe diameter, flow rate, length and fittings influence pressure loss in a preliminary water-system estimate.",
            "answer": "Pressure loss rises as flow increases and generally falls as the inside diameter increases. Pipe material, route length, fittings, elevation and temperature also affect the result, so a nominal pipe label alone is not enough for design.",
            "steps": [("Set the target flow", "Use the fixture demand or equipment requirement, not an arbitrary maximum flow."), ("Confirm inside diameter", "Use the actual product dimensions because nominal pipe sizes do not all have the same inside diameter."), ("Add route effects", "Include equivalent length for elbows, valves, meters and other restrictions."), ("Check the system", "Compare the estimate with available pressure and the local plumbing requirements.")],
            "formula": "pressure loss depends on flow, inside diameter, length, roughness and fittings",
            "example": "Two pipes with the same nominal label can have different flow performance when their actual inside diameters or materials differ.",
            "mistakes": "Using outside diameter, ignoring fittings, treating static pressure as flowing pressure, and sizing a pump from a preliminary pipe estimate.",
            "faqs": [("Why does a smaller pipe lose more pressure?", "The smaller flow area creates more resistance for the same flow rate."), ("Should I include every elbow?", "Include meaningful fittings and use an equivalent-length method appropriate to the pipe system."), ("Is this a final plumbing design?", "No. Verify code, materials, pressure and fixture requirements before installation.")],
        },
        {
            "slug": "residential-circuit-load-planning-guide",
            "title": "Residential Circuit Load Planning Guide",
            "category": "Electrical Planning",
            "topic": "electrical",
            "parent": "electrical-load-calculator",
            "description": "Organize lighting, receptacle, appliance, motor and HVAC loads before a residential electrical review.",
            "answer": "A useful early load schedule lists each load, its voltage, current or wattage, operating pattern and circuit location. The schedule helps reveal peak demand, but local code demand factors and conductor rules still control the final design.",
            "steps": [("Build an inventory", "List fixed appliances, HVAC, lighting, receptacles, pumps and motors."), ("Normalize units", "Convert the nameplate information into watts or volt-amperes consistently."), ("Mark operating type", "Identify continuous, intermittent, motor-starting and emergency loads."), ("Separate circuits", "Group loads by circuit and have service and feeder calculations reviewed.")],
            "formula": "watts = volts × amps × power factor",
            "example": "A 240 V load drawing 20 A at power factor 0.9 is approximately 4,320 W, not 4,800 W, before code-specific demand treatment.",
            "mistakes": "Adding amps across different voltages, forgetting HVAC or water-heating loads, and using a calculator output as a breaker selection.",
            "faqs": [("Do receptacles have a fixed wattage?", "Their design load depends on the applicable code method and the connected equipment assumptions."), ("What is a continuous load?", "It is a load expected to run for the duration defined by the applicable electrical rules."), ("Can I use this for a permit?", "Use it as a preparation worksheet and have the final design checked by a qualified electrician.")],
        },
        {
            "slug": "heat-pump-btu-sizing-planning-guide",
            "title": "Heat Pump BTU Sizing Planning Guide",
            "category": "HVAC Planning",
            "topic": "hvac",
            "parent": "hvac-btu-calculator",
            "description": "Estimate an early heat-pump capacity range while checking heating and cooling loads, climate and low-temperature performance.",
            "answer": "Heat-pump sizing must consider both cooling and heating loads. Climate, insulation, windows, air leakage and outdoor design temperature can make the heating requirement very different from a simple cooling-area estimate.",
            "steps": [("Separate loads", "Estimate cooling and heating needs rather than using one number for both."), ("Check design climate", "Use local outdoor design temperatures and the equipment performance data at those conditions."), ("Review building envelope", "Account for insulation, windows, air leakage, ceiling height and solar exposure."), ("Confirm equipment", "Compare rated capacity, staging, backup heat and airflow with a room-by-room load calculation.")],
            "formula": "early capacity range = conditioned area × clearly labeled planning factor",
            "example": "A 1,200 ft² home may produce a rough screening range, but two homes with the same area can require very different equipment because of envelope and climate differences.",
            "mistakes": "Sizing only from square footage, ignoring heating capacity at low temperature, and choosing the largest available unit.",
            "faqs": [("Should heating or cooling control the size?", "The controlling load depends on the climate and building; both should be evaluated."), ("Does insulation reduce required BTU?", "Better insulation and air sealing can reduce load, but the actual effect should be calculated."), ("What should I ask an installer for?", "Ask for a documented room-by-room load calculation and equipment performance at design conditions.")],
        },
        {
            "slug": "concrete-footing-and-pad-volume-guide",
            "title": "Concrete Footing and Pad Volume Guide",
            "category": "Concrete Planning",
            "topic": "concrete",
            "parent": "concrete-footing-calculator",
            "description": "Estimate concrete for isolated pads and rectangular footing sections by separating geometry, ordering quantity and structural design.",
            "answer": "A rectangular pad or footing is estimated by multiplying length, width and depth. Use separate calculations for different sections, convert cubic feet to cubic yards, then review waste and supplier minimums.",
            "steps": [("Measure finished geometry", "Use the specified concrete dimensions, not an oversized excavation unless it is intentionally part of the pour."), ("Split sections", "Calculate pads, grade beams and steps separately when their dimensions differ."), ("Convert volume", "Add cubic-foot results and divide by 27 for cubic yards."), ("Review ordering", "Add a visible allowance and check delivery minimums before placing an order.")],
            "formula": "volume(ft³) = length × width × depth; volume(yd³) = ft³ ÷ 27",
            "example": "A 3 ft × 3 ft × 1 ft pad is 9 ft³, or 0.33 yd³, before allowance and any supplier short-load charge.",
            "mistakes": "Using excavation volume without checking forms, averaging different footing sizes, and using quantity calculations to select reinforcement or footing dimensions.",
            "faqs": [("Should I round a small pad order?", "Yes. Ready-mix minimums and access costs can dominate small quantities."), ("Can this calculate a pier?", "Only if the geometry matches the selected shape; cylindrical piers need a cylinder formula."), ("Does the result include reinforcement?", "No. Rebar and anchor details are separate design and quantity decisions.")],
        },
        {
            "slug": "concrete-ordering-and-truck-load-guide",
            "title": "Concrete Ordering: Cubic Yards and Truck Loads",
            "category": "Concrete Planning",
            "topic": "concrete",
            "parent": "concrete-volume-calculator",
            "description": "Turn measured concrete volume into a practical ready-mix order while checking truck capacity, access and site readiness.",
            "answer": "Calculate the placed volume first, convert it to cubic yards and keep the allowance visible. The supplier then determines truck capacity, minimum load, delivery window, mix availability and short-load charges.",
            "steps": [("Finish the quantity", "Use actual dimensions and split irregular areas into measurable sections."), ("Add allowance", "Account for uneven subgrade, form variation and small losses without hiding the percentage."), ("Check supplier rules", "Ask about minimum load, truck capacity, washout, slump and mix availability."), ("Prepare the pour", "Confirm access, crew, forms, reinforcement, tools and weather before the truck arrives.")],
            "formula": "order quantity = measured volume × (1 + allowance)",
            "example": "A measured 5.8 yd³ with a 7% planning allowance becomes 6.21 yd³, then the supplier may require a practical order quantity based on its dispatch rules.",
            "mistakes": "Ordering from footprint only, forgetting thickness variation, waiting until the truck arrives to solve access, and assuming every supplier uses the same minimum load.",
            "faqs": [("How much concrete is in a truck?", "Capacity varies by truck, supplier, mix and legal payload; ask the local supplier."), ("Should I order extra?", "A visible allowance is prudent, but excessive over-ordering creates waste and disposal problems."), ("Does the calculator schedule the pour?", "No. Delivery timing, crew, access and weather require project coordination.")],
        },
        {
            "slug": "rebar-weight-and-purchase-length-guide",
            "title": "Rebar Weight and Purchase Length Guide",
            "category": "Concrete & Reinforcement",
            "topic": "concrete",
            "parent": "rebar-weight-calculator",
            "description": "Estimate reinforcement weight from bar size, count and length while separating theoretical takeoff from laps, bends and cutting waste.",
            "answer": "Rebar weight is approximately bar unit weight multiplied by total length. A purchase estimate must also consider stock lengths, laps, hooks, bends, chairs, splice details and cutting waste.",
            "steps": [("Confirm designation", "Keep US bar numbers and metric diameters as separate systems."), ("Calculate total length", "Multiply bar count by bar length and add lap or hook allowances from the schedule."), ("Apply unit weight", "Use a reliable table or manufacturer data for the selected bar."), ("Plan purchasing", "Round to available stock lengths and include cut optimization and waste.")],
            "formula": "weight = total bar length × unit weight",
            "example": "If 40 bars are each 12 ft long, the theoretical total is 480 linear feet before laps, bends and cutting optimization.",
            "mistakes": "Confusing diameter with nominal bar designation, forgetting laps, and using theoretical weight as a complete purchase list.",
            "faqs": [("Are #4 rebar and 12 mm rebar identical?", "They are different designations and should not be treated as interchangeable without the project specification."), ("Does weight include tie wire?", "No. Tie wire, chairs and accessories are separate items."), ("Can I use this for structural design?", "No. Use the structural drawings or qualified design for size, spacing, cover and detailing.")],
        },
        {
            "slug": "hvac-room-by-room-load-checklist",
            "title": "HVAC Room-by-Room Load Checklist",
            "category": "HVAC Planning",
            "topic": "hvac",
            "parent": "hvac-btu-calculator",
            "description": "Collect the room measurements and building details needed before requesting a proper heating and cooling load calculation.",
            "answer": "A room-by-room load estimate needs more than floor area. Record exterior walls, windows, orientation, ceiling height, insulation, infiltration, occupancy and connected equipment so the final design is based on the building rather than a generic multiplier.",
            "steps": [("Measure each room", "Record length, width, ceiling height and whether each wall borders outdoors or an unconditioned space."), ("Count openings", "Measure window and door sizes and note orientation and shading."), ("Record envelope data", "Document insulation, roof exposure, air sealing and construction type where known."), ("Record internal gains", "Note occupants, lighting, appliances and ventilation requirements.")],
            "formula": "room load = transmission + solar gain + infiltration + internal gains",
            "example": "Two rooms with equal floor area can have different loads when one has a large west-facing window and the other is surrounded by conditioned rooms.",
            "mistakes": "Using one whole-house multiplier, ignoring ceiling height, omitting ventilation and assuming all windows perform the same.",
            "faqs": [("Why measure room by room?", "It helps size distribution and equipment so one room is not overcooled while another remains uncomfortable."), ("What if insulation is unknown?", "Record the uncertainty and use conservative documented assumptions until the assembly is verified."), ("Is this enough to buy equipment?", "No. It is a data-collection checklist for a proper load calculation.")],
        },
        {
            "slug": "electrical-voltage-amp-watt-conversion-guide",
            "title": "Voltage, Amps and Watts: Electrical Conversion Guide",
            "category": "Electrical Planning",
            "topic": "electrical",
            "parent": "electrical-load-calculator",
            "description": "Convert voltage, current and power correctly for a preliminary electrical load estimate, including the difference between watts and volt-amperes.",
            "answer": "For a simple single-phase resistive load, watts are approximately volts multiplied by amps. Motors and electronic equipment can have power factor, so apparent power in volt-amperes may be higher than real power in watts.",
            "steps": [("Read the nameplate", "Record voltage, current, watts and power factor if listed."), ("Choose the right equation", "Use W = V × A for a simple resistive estimate, or VA = V × A when apparent power is needed."), ("Check phase", "Three-phase systems require the appropriate phase relationship and should not use a single-phase shortcut."), ("Apply code review", "Use the result as an estimate, not as a final breaker or conductor decision.")],
            "formula": "single-phase W = V × A × power factor; VA = V × A",
            "example": "A 120 V, 5 A resistive load is about 600 W. If its power factor is 0.8, the same 600 VA apparent load represents about 480 W real power.",
            "mistakes": "Using watts and VA interchangeably, ignoring phase, and choosing protection from wattage alone.",
            "faqs": [("What is power factor?", "It describes the relationship between real power and apparent power in AC equipment."), ("Why do motors list different values?", "Starting and running conditions, efficiency and power factor affect their electrical demand."), ("Can I size a wire from this page?", "No. Conductor sizing also depends on ampacity, temperature, installation method and local rules.")],
        },
    ]
