from __future__ import annotations


def seo_guides() -> list[dict]:
    return [
        {
            "slug": "residential-water-pipe-sizing-guide",
            "title": "How to Size a Residential Water Pipe",
            "category": "Plumbing Planning",
            "topic": "plumbing",
            "parent": "pipe-flow-calculator",
            "description": "Estimate a starting point for residential water-pipe sizing by checking demand, length, elevation and pressure instead of choosing a diameter by guesswork.",
            "answer": "Pipe sizing starts with fixture demand, available pressure, pipe length, elevation change, fittings and the material's friction characteristics. A simple calculator can screen options, but final sizing should follow the local plumbing code and the actual system design.",
            "steps": [
                ("List the demand", "Count fixtures and identify simultaneous-use assumptions rather than adding every fixture as if it runs at once."),
                ("Measure the route", "Include developed pipe length, fittings and meaningful elevation change."),
                ("Check pressure", "Start with static pressure, then allow for pressure loss through the meter, backflow device, valves and pipe."),
                ("Compare sizes", "Use the calculator for a transparent comparison, then verify the selected pipe with local code and manufacturer data."),
            ],
            "formula": "available pressure = source pressure - elevation loss - fitting loss - pipe friction loss",
            "example": "A long run with several elbows can perform worse than a short run of the same nominal diameter, even when the fixture count is identical.",
            "mistakes": "Using outside diameter as though it were inside diameter, ignoring elevation, sizing from maximum fixture count without a demand method, or treating a preliminary estimate as a permitted plumbing design.",
            "faqs": [
                ("Does a larger pipe always improve pressure?", "It can reduce friction loss, but source pressure, fittings, elevation and the rest of the system still control performance."),
                ("Should hot and cold lines be sized the same?", "Not necessarily. Demand, routing and local requirements can differ."),
                ("What should I verify before installation?", "Verify local code, approved materials, pressure limits, connection details and the authority having jurisdiction."),
            ],
        },
        {
            "slug": "electrical-load-estimate-guide",
            "title": "How to Estimate Electrical Load Before a Project",
            "category": "Electrical Planning",
            "topic": "electrical",
            "parent": "electrical-load-calculator",
            "description": "Build a preliminary electrical load estimate from voltage, current, power factor and operating conditions while keeping code calculations separate.",
            "answer": "A preliminary load estimate identifies the approximate watts or volt-amperes used by equipment. It does not replace a service-load calculation, conductor sizing, overcurrent protection or a licensed electrical review.",
            "steps": [
                ("Inventory equipment", "Record nameplate voltage, current, watts, motor data and whether each load is continuous."),
                ("Convert consistently", "Use watts or volt-amperes consistently; for single-phase loads, apparent power is commonly estimated as volts × amps."),
                ("Group operating loads", "Separate general lighting, receptacles, HVAC, motors and special equipment before applying project-specific demand rules."),
                ("Review the design", "Have the final service, feeder, breaker and conductor decisions checked against local electrical code."),
            ],
            "formula": "single-phase apparent power (VA) = volts × amps",
            "example": "A 120 V appliance drawing 8 A represents about 960 VA before any power-factor or demand adjustment.",
            "mistakes": "Adding nameplate amps from different voltages without conversion, ignoring motors and continuous loads, or selecting a breaker from the calculator result alone.",
            "faqs": [
                ("Are watts and VA the same?", "They can differ when power factor is not 1.0, especially with motors and electronic equipment."),
                ("Does a larger breaker solve overloads?", "No. Protection must coordinate with conductor ampacity, equipment ratings and the applicable code."),
                ("Can a homeowner use this for a permit design?", "Use it as an early planning aid only; final electrical design should be reviewed by a qualified professional."),
            ],
        },
        {
            "slug": "hvac-btu-sizing-basics-guide",
            "title": "HVAC BTU Sizing Basics for Early Planning",
            "category": "HVAC Planning",
            "topic": "hvac",
            "parent": "hvac-btu-calculator",
            "description": "Use area, climate and building factors to create an early HVAC capacity estimate without oversizing from square footage alone.",
            "answer": "BTU/h is a rate of heating or cooling capacity. Floor area can produce a rough screening estimate, but climate, insulation, windows, orientation, air leakage, occupancy and internal gains can change the required capacity substantially.",
            "steps": [
                ("Measure conditioned area", "Separate conditioned rooms from garages, unconditioned spaces and areas with different loads."),
                ("Choose a screening factor", "Use a clearly labeled regional or building-condition assumption rather than presenting it as a universal rule."),
                ("Adjust the context", "Consider windows, ceiling height, insulation, solar exposure, occupancy and ventilation."),
                ("Confirm professionally", "Use a recognized load calculation method such as Manual J or the applicable local method before sizing equipment."),
            ],
            "formula": "screening capacity(BTU/h) = conditioned area(ft²) × planning factor(BTU/h per ft²)",
            "example": "A 1,000 ft² early screening at an illustrative 25 BTU/h per ft² gives 25,000 BTU/h, but the final design may differ materially after a room-by-room load calculation.",
            "mistakes": "Sizing from floor area alone, rounding up to a very large unit, ignoring humidity and ventilation, and treating equipment capacity as equal to actual room load.",
            "faqs": [
                ("Is bigger HVAC equipment better?", "Oversizing can reduce run time, comfort and humidity control; proper load calculation matters more than simply choosing a larger unit."),
                ("What is Manual J?", "It is a recognized residential heating and cooling load-calculation method used to estimate building loads."),
                ("Can this calculator choose my heat pump?", "No. Use it for early planning, then confirm capacity, airflow, climate performance and installation requirements."),
            ],
        },
        {
            "slug": "rebar-spacing-and-quantity-planning-guide",
            "title": "Rebar Spacing and Quantity Planning Guide",
            "category": "Concrete & Reinforcement",
            "topic": "concrete",
            "parent": "rebar-spacing-calculator",
            "description": "Estimate the number of reinforcement bars from slab dimensions, edge allowance and spacing while keeping cover and structural design separate.",
            "answer": "A planning count can be estimated by dividing the usable width by the maximum spacing and rounding up, then adding the first bar position. Actual reinforcement requires design decisions about bar size, cover, laps, support, openings and loading.",
            "steps": [
                ("Identify the bar direction", "Bars spaced across a width are counted from the usable dimension perpendicular to their length."),
                ("Subtract edge allowance", "Keep the assumed edge distance visible instead of hiding it in the count."),
                ("Divide by spacing", "Calculate intervals, round up to avoid exceeding the planning spacing, then add the starting position."),
                ("Check the schedule", "Confirm bar size, grade, cover, laps and supports against the structural drawings or local requirements."),
            ],
            "formula": "bar count ≈ ceiling((usable width ÷ spacing)) + 1",
            "example": "With 18 ft of usable width and bars at 12 in on center, the preliminary count is based on 18 ft ÷ 1 ft intervals, then adjusted for the first bar and edge placement.",
            "mistakes": "Counting bars along the wrong dimension, ignoring cover, forgetting laps and openings, or treating a quantity estimate as a reinforcement design.",
            "faqs": [
                ("Does closer spacing always make a slab safe?", "Not by itself. Bar size, depth, concrete, support, loads and detailing all matter."),
                ("Do I include lap length?", "Yes for purchasing length, but lap requirements must come from the design or applicable standard."),
                ("Can I use US bar numbers with metric diameters?", "Keep the systems distinct. Use the actual bar designation and project specification."),
            ],
        },
        {
            "slug": "concrete-yield-and-batch-volume-guide",
            "title": "Concrete Yield and Batch Volume: What to Check",
            "category": "Concrete Planning",
            "topic": "concrete",
            "parent": "concrete-yield-calculator",
            "description": "Check concrete yield from measured ingredients or product data and understand why theoretical batch volume can differ from placed volume.",
            "answer": "Concrete yield is the volume produced by a batch after ingredients are combined. Yield checks are useful for estimating bags, batches and short pours, but they do not replace a specified mix design or quality-control testing.",
            "steps": [
                ("Define the batch", "Record the cementitious material, aggregate, water and admixtures used in the batch."),
                ("Use product data", "For premixed products, use the manufacturer's published yield instead of inferring volume from bag weight."),
                ("Compare to project volume", "Divide required placed volume by batch yield and round up to complete batches."),
                ("Allow for reality", "Review spillage, uneven subgrade, mixer loss, moisture and access before ordering."),
            ],
            "formula": "number of batches = required placed volume ÷ usable yield per batch",
            "example": "If a batch produces 2.0 ft³ of usable concrete and the project needs 9.0 ft³, the theoretical result is 4.5 batches, so five complete batches may be needed before checking the allowance.",
            "mistakes": "Confusing dry ingredient volume with finished concrete yield, assuming all bags have the same yield, and using a quantity tool to design structural concrete.",
            "faqs": [
                ("Why is dry volume different from finished volume?", "Particles pack differently and voids are filled as the materials combine; the product yield or mix calculation controls."),
                ("Should I round batches up?", "Yes, a shortage during a continuous pour can be difficult to correct."),
                ("Does this determine concrete strength?", "No. Strength depends on the specified materials, proportions, placement, curing and testing."),
            ],
        },
        {
            "slug": "drainage-slope-planning-guide",
            "title": "Drainage Slope Planning: Rise, Run and Flow",
            "category": "Site & Plumbing Planning",
            "topic": "plumbing",
            "parent": "drainage-slope-calculator",
            "description": "Calculate drainage grade from rise and run, then check whether the result matches the pipe, surface and local installation requirements.",
            "answer": "Slope is the vertical change divided by the horizontal run. The same percentage can represent very different elevation changes depending on the route length, so both grade and actual rise should be reported.",
            "steps": [
                ("Measure the run", "Use the horizontal distance, not the sloped surface length, for a basic grade calculation."),
                ("Measure the rise", "Use the elevation difference between the two points in consistent units."),
                ("Calculate grade", "Divide rise by run and multiply by 100 for percent slope."),
                ("Check the application", "Verify minimum slope, invert elevations, cleanouts, transitions and local requirements for the actual drainage system."),
            ],
            "formula": "grade(%) = rise ÷ run × 100",
            "example": "A 6 in fall over a 20 ft run is 0.5 ft ÷ 20 ft = 2.5% grade.",
            "mistakes": "Using the pipe length as horizontal run, mixing inches and feet, assuming more slope always fixes drainage, or ignoring low points and outlet elevations.",
            "faqs": [
                ("Is percentage slope the same as pitch?", "They describe related geometry, but the preferred notation depends on the application."),
                ("Can I use this for sewer pipe design?", "Use it for preliminary geometry only; pipe size, flow, bedding, cleanouts and code requirements still need review."),
                ("Why does a long run need careful elevation planning?", "Small grade errors accumulate over distance and can create an outlet or low-point problem."),
            ],
        },
        {
            "slug": "cmu-mortar-quantity-estimate-guide",
            "title": "How to Estimate Mortar for Concrete Block Walls",
            "category": "Masonry Planning",
            "topic": "concrete",
            "parent": "cmu-mortar-calculator",
            "description": "Estimate mortar materials for CMU joints from wall area and joint assumptions while keeping block design and reinforcement separate.",
            "answer": "Mortar quantity depends on block size, wall area, joint thickness, workmanship and the product's yield. A planning estimate should expose the assumed mortar volume and then convert it using the manufacturer's bag yield.",
            "steps": [
                ("Calculate net wall area", "Subtract large openings from the gross block wall area."),
                ("Choose block and joint assumptions", "Use the actual CMU size and specified bed and head joint dimensions."),
                ("Estimate mortar volume", "Use a transparent joint-volume or product-yield assumption rather than a hidden rule of thumb."),
                ("Round complete bags", "Use the current bag yield, round up, and retain allowance for joints, waste and cleanup."),
            ],
            "formula": "mortar bags = estimated mortar volume ÷ published yield per bag",
            "example": "If the joint estimate is 6.4 ft³ and a mortar product yields 0.75 ft³ per bag, the theoretical requirement is 8.53 bags, so nine bags are needed before a site allowance.",
            "mistakes": "Using block count as a direct substitute for mortar volume, forgetting openings, mixing grout with mortar, and selecting mortar type without checking the specification.",
            "faqs": [
                ("Is mortar the same as grout?", "No. They serve different purposes and should not be substituted without a project specification."),
                ("Does a thicker joint use much more mortar?", "Yes, joint thickness and workmanship can significantly change the quantity."),
                ("Does this size the wall?", "No. Structural stability, reinforcement, bond beams, lateral loads and foundation support require design review."),
            ],
        },
        {
            "slug": "electrical-voltage-drop-planning-guide",
            "title": "Voltage Drop Planning for Long Electrical Runs",
            "category": "Electrical Planning",
            "topic": "electrical",
            "parent": "electrical-load-calculator",
            "description": "Understand why conductor length, current, material and conductor size affect voltage drop before final circuit design.",
            "answer": "Voltage drop increases with current and conductor resistance. Longer circuits have a longer round-trip path, so a load that works on a short run may perform poorly when the same conductor is extended.",
            "steps": [
                ("Record the load", "Use the expected operating current and starting characteristics for motors or compressors."),
                ("Measure the circuit length", "For a two-wire circuit, remember that current travels out and back."),
                ("Select conductor data", "Use the actual conductor material, temperature rating, size and installation conditions."),
                ("Review the result", "Compare the calculated drop with equipment guidance and local code before selecting conductors or protection."),
            ],
            "formula": "voltage drop ≈ current × circuit resistance",
            "example": "If a circuit's round-trip resistance is 0.12 ohm and operating current is 15 A, the approximate drop is 1.8 V before checking temperature and installation details.",
            "mistakes": "Using one-way length only, mixing conductor material data, ignoring motor starting current, or increasing breaker size to compensate for undersized conductors.",
            "faqs": [
                ("Does a bigger breaker reduce voltage drop?", "No. Breaker size does not reduce conductor resistance or voltage drop."),
                ("Why does motor starting matter?", "Starting current can be much higher than running current and can create temporary voltage sag."),
                ("Can this replace an electrical inspection?", "No. It is a planning aid; final conductor and protection choices need qualified review."),
            ],
        },
    ]
