from __future__ import annotations

def seo_guides() -> list[dict]:
    return [
        {
            "slug": "how-to-calculate-concrete-driveway-material",
            "title": "How to Calculate Concrete for a Driveway",
            "category": "Concrete & Masonry", "topic": "concrete", "parent": "concrete-driveway-calculator",
            "description": "Estimate driveway concrete volume from length, width and slab thickness before requesting supplier quotes.",
            "answer": "Multiply driveway length by width by thickness in feet, then divide by 27 to convert cubic feet to cubic yards. Split irregular driveways into measurable sections.",
            "steps": [("Measure each section.", "Use feet and separate rectangular areas."), ("Convert thickness.", "Divide inches by 12."), ("Calculate volume.", "Multiply length × width × thickness."), ("Convert and review.", "Divide by 27, then confirm allowance and ordering requirements.")],
            "formula": "cubic yards = length(ft) × width(ft) × thickness(ft) ÷ 27",
            "example": "A 40 ft × 12 ft driveway at 5 in thick is about 7.41 yd³ before an allowance.",
            "mistakes": "Do not use a generic thickness without checking the project design, base conditions and local requirements.",
            "faqs": [("Should driveway thickness be uniform?", "The design may vary by site, loads and reinforcement; confirm with a qualified professional."), ("Can I use this for an apron?", "Calculate the apron as a separate section and add it to the driveway volume."), ("Is this an engineering design?", "No. It is a material-planning estimate only.")],
        },
        {
            "slug": "how-to-calculate-soil-for-raised-bed",
            "title": "How to Calculate Soil for a Raised Bed",
            "category": "Landscaping", "topic": "landscaping", "parent": "soil-calculator",
            "description": "Calculate soil volume for raised garden beds using inside length, width and fill depth.",
            "answer": "Multiply the inside length by inside width by the intended soil depth in feet. Convert cubic feet to cubic yards by dividing by 27, or divide by the bag volume for bag estimates.",
            "steps": [("Measure inside dimensions.", "Use the actual fill area, not the outside frame size."), ("Choose fill depth.", "Account for the finished soil level."), ("Calculate cubic feet.", "Multiply length × width × depth."), ("Convert quantity.", "Use cubic yards or the exact bag volume.")],
            "formula": "soil volume = length × width × depth",
            "example": "A 4 ft × 8 ft bed filled 1 ft deep needs 32 ft³, or about 1.19 yd³.",
            "mistakes": "Do not divide by 27 when you need bags unless you also use the bag's printed cubic-foot volume.",
            "faqs": [("Should I include settling?", "Bulk soil can settle, so ask the supplier how delivered volume is represented."), ("Can beds have different depths?", "Split the bed into sections and calculate each depth separately."), ("How do I calculate bags?", "Divide total cubic feet by the cubic feet per bag and round up.")],
        },
        {
            "slug": "how-to-calculate-roofing-squares",
            "title": "How to Calculate Roofing Squares",
            "category": "Roofing, Decks & Fences", "topic": "roofing-decks-fences", "parent": "roofing",
            "description": "Convert estimated roof surface area into roofing squares before checking bundles, underlayment and supplier requirements.",
            "answer": "One roofing square represents 100 square feet of roof surface. Divide the estimated surface area by 100, then plan waste and product-specific bundle coverage separately.",
            "steps": [("Estimate roof surface area.", "Use measured roof planes or a suitable plan-based method."), ("Divide by 100.", "This gives the raw number of squares."), ("Add layout allowance.", "Account for cuts, valleys, hips and starter material."), ("Check package coverage.", "Bundle counts vary by product and exposure.")],
            "formula": "roofing squares = roof surface area(ft²) ÷ 100",
            "example": "A 2,400 ft² roof surface equals 24 squares before waste and accessory calculations.",
            "mistakes": "Do not assume one shingle bundle always covers one-third of a square; package coverage varies by product.",
            "faqs": [("Are accessories included in squares?", "No. Starter, ridge, valley, underlayment and flashing need separate planning."), ("Should I measure complex roofs myself?", "Use safe measurements or professional roof measurement for complex or inaccessible roofs."), ("Does waste change square count?", "The raw squares remain geometric; waste changes the purchase quantity.")],
        },
        {
            "slug": "how-to-calculate-bathroom-tile",
            "title": "How to Calculate Tile for a Bathroom",
            "category": "Flooring & Tile", "topic": "flooring", "parent": "bathroom-tile-calculator",
            "description": "Estimate bathroom floor and wall tile by separating surfaces, openings, waste and full-box rounding.",
            "answer": "Calculate each tiled surface separately, subtract only meaningful areas that will not receive tile, add a visible waste allowance, then round to complete boxes.",
            "steps": [("List tiled surfaces.", "Separate floor, shower walls, backsplash and other areas."), ("Measure each rectangle.", "Use consistent units."), ("Subtract exclusions.", "Remove large openings or untiled areas."), ("Add waste and round.", "Use the exact box coverage for the selected tile.")],
            "formula": "purchase area = total tiled area × (1 + waste rate)",
            "example": "A 60 ft² bathroom floor with 12% planning waste requires 67.2 ft² before package rounding.",
            "mistakes": "Do not combine floor and wall areas when they use different tile, box coverage or layout patterns.",
            "faqs": [("Should shower niches be measured separately?", "Yes. Complex cuts can affect waste and should be visible in the plan."), ("Do I subtract the toilet footprint?", "For basic planning, small fixture areas are often left in because cuts and breakage offset the geometric subtraction."), ("Is waterproofing included?", "No. Waterproofing and substrate preparation are separate project requirements.")],
        },
        {
            "slug": "how-to-estimate-deck-cost",
            "title": "How to Estimate Deck Material Cost",
            "category": "Roofing, Decks & Fences", "topic": "roofing-decks-fences", "parent": "deck",
            "description": "Build an early deck budget by separating boards, framing, hardware, stairs, railings and labor instead of using one hidden rate.",
            "answer": "Estimate the deck area and material quantities first, then price each major component separately. A useful early budget should show assumptions for decking, framing, fasteners, stairs, railing and labor.",
            "steps": [("Measure the deck.", "Record length, width, height and stairs."), ("Estimate quantities.", "Plan boards, joists, posts, beams, hardware and railing."), ("Price components.", "Use current local supplier prices for the selected products."), ("Add labor and contingency.", "Keep labor, permits and site conditions visible.")],
            "formula": "early budget = materials + labor + permits + site allowances",
            "example": "A deck budget is more useful when decking, framing, railing and stairs are separate line items rather than one unexplained square-foot rate.",
            "mistakes": "Do not treat an online square-foot price as a quote. Design, height, access, stairs, railing and local code requirements can change the total substantially.",
            "faqs": [("Does the calculator replace a quote?", "No. It is an early planning range before supplier and contractor quotes."), ("Should stairs be separate?", "Yes. Stairs can materially change framing, railing and labor."), ("Do I need a permit?", "Permit requirements vary by location and project scope; check local authorities.")],
        },
    ]
