def seo_pages():
    return [
        {
            "slug": "soil-calculator",
            "title": "Soil Calculator",
            "category": "Landscape Materials",
            "parent": "mulch",
            "description": "Estimate soil volume for beds, planters and leveling projects from measured area and target depth.",
            "formula": "soil volume = area × depth",
            "example": "A 12 × 8 ft bed filled 6 in deep needs about 48 ft³, or roughly 1.78 yd³, before settling allowance.",
            "uses": ["Raised beds", "Garden beds", "Lawn leveling", "Planter filling"],
            "faqs": [
                ("How deep should garden soil be?", "Depth depends on the project and plant type. Enter the depth you actually plan to install rather than relying on a generic default."),
                ("Should I allow for settling?", "Yes when the material will compact or settle. A modest planning allowance can reduce the chance of coming up short."),
                ("Can I calculate several beds together?", "Yes. Calculate each bed separately and add the volumes, especially when depths differ."),
            ],
        },
        {
            "slug": "topsoil-calculator",
            "title": "Topsoil Calculator",
            "category": "Landscape Materials",
            "parent": "mulch",
            "description": "Estimate cubic yards of topsoil needed for lawns, beds and grading using measured square footage and depth.",
            "formula": "cubic yards = square feet × depth in feet ÷ 27",
            "example": "1,000 ft² covered 2 in deep is about 6.17 yd³ before compaction or grading allowance.",
            "uses": ["New lawns", "Garden beds", "Low-spot filling", "Landscape grading"],
            "faqs": [
                ("How many yards of topsoil cover 1,000 square feet?", "Coverage depends entirely on depth. At 2 inches, the geometric volume is about 6.17 cubic yards."),
                ("Does topsoil compact?", "Yes. Delivered material may settle after spreading, watering and traffic, so a project-specific allowance can be useful."),
                ("Should I measure slopes differently?", "For modest slopes, surface area may be close to plan area. Steeper sites benefit from more careful section measurements."),
            ],
        },
        {
            "slug": "paver-calculator",
            "title": "Paver Calculator",
            "category": "Landscape Materials",
            "parent": "tile",
            "description": "Estimate paver count from project area, individual paver dimensions and a visible cutting and breakage allowance.",
            "formula": "pavers = project area ÷ paver face area, then add waste",
            "example": "A 200 ft² patio using 6 × 9 in pavers needs about 534 pieces geometrically before cutting and breakage allowance.",
            "uses": ["Patios", "Walkways", "Small plazas", "Garden paths"],
            "faqs": [
                ("How much waste should I add for pavers?", "Simple rectangular layouts may need less than projects with curves, borders or complex patterns. Use the layout to choose the allowance."),
                ("Do I include joint spacing?", "Manufactured paver systems often have built-in spacing assumptions. Follow the product system rather than manually subtracting every joint."),
                ("Does this include base material?", "No. Paver count and base aggregate are different calculations and should be planned separately."),
            ],
        },
        {
            "slug": "garden-bed-soil-calculator",
            "title": "Garden Bed Soil Calculator",
            "category": "Landscape Materials",
            "parent": "mulch",
            "description": "Calculate soil volume for rectangular garden beds and raised beds using inside dimensions and fill depth.",
            "formula": "bed volume = inside length × inside width × fill depth",
            "example": "A raised bed with 8 × 4 ft inside dimensions filled 10 in deep needs about 26.7 ft³ before settling allowance.",
            "uses": ["Raised vegetable beds", "Flower beds", "Herb gardens", "Planter boxes"],
            "faqs": [
                ("Should I use inside or outside bed dimensions?", "Use the inside dimensions because wall thickness does not hold soil."),
                ("Can I mix compost and soil?", "Yes. First estimate total fill volume, then divide that volume according to your chosen mix ratio."),
                ("Do I fill a raised bed to the very top?", "Usually not. Leave the freeboard you want, and use the actual intended soil depth in the calculation."),
            ],
        },
        {
            "slug": "river-rock-calculator",
            "title": "River Rock Calculator",
            "category": "Landscape Materials",
            "parent": "gravel",
            "description": "Estimate river rock volume and approximate bulk quantity from area, installation depth and supplier density information.",
            "formula": "rock volume = area × depth",
            "example": "A 300 ft² landscape area at 2 in deep is 50 ft³, or about 1.85 yd³, before edge and settlement allowance.",
            "uses": ["Landscape beds", "Drainage strips", "Dry creek features", "Decorative borders"],
            "faqs": [
                ("How deep should river rock be?", "Depth depends on stone size, fabric, traffic and appearance. Use the depth specified for your project or supplier recommendation."),
                ("Can cubic yards be converted directly to tons?", "Only with a density assumption. Use the supplier’s actual bulk density because stone type and moisture affect weight."),
                ("Should I add extra rock?", "A small allowance can help with uneven grade, settlement and edge transitions, especially on irregular beds."),
            ],
        },
        {
            "slug": "roof-area-calculator",
            "title": "Roof Area Calculator",
            "category": "Roofing & Exterior",
            "parent": "roofing",
            "description": "Estimate simple roof surface area from building footprint and roof slope factor for early material planning.",
            "formula": "roof area ≈ footprint area × slope factor",
            "example": "A 30 × 40 ft simple gable footprint is 1,200 ft². A slope factor above 1 increases the actual roof surface area.",
            "uses": ["Simple gable roofs", "Early shingle budgets", "Underlayment planning", "Roof replacement estimates"],
            "faqs": [
                ("Is roof area the same as house floor area?", "No. Roof slope increases surface area, and overhangs can make the roof larger than the building footprint."),
                ("Can this handle complex roofs?", "Only approximately. Hips, valleys, dormers and intersecting roof planes should be measured as separate surfaces."),
                ("Is this a structural calculator?", "No. It is for material planning only and does not evaluate loads, framing or code compliance."),
            ],
        },
        {
            "slug": "shingle-calculator",
            "title": "Shingle Calculator",
            "category": "Roofing & Exterior",
            "parent": "roofing",
            "description": "Estimate roofing squares and shingle bundles from roof area, waste allowance and bundles per square.",
            "formula": "roofing squares = roof area ÷ 100",
            "example": "A 2,000 ft² roof is 20 roofing squares before waste. At three bundles per square, that is 60 bundles before allowance.",
            "uses": ["Asphalt shingles", "Roof replacement budgets", "Garage roofs", "Simple additions"],
            "faqs": [
                ("What is a roofing square?", "One roofing square is 100 square feet of roof surface area."),
                ("How many bundles are in a square?", "Many asphalt products use three bundles per square, but some use more. Check the exact product packaging."),
                ("How much shingle waste should I add?", "Simple gable roofs may need less than complex hip-and-valley roofs. Use the roof geometry and installer guidance to choose the allowance."),
            ],
        },
        {
            "slug": "roofing-material-calculator",
            "title": "Roofing Material Calculator",
            "category": "Roofing & Exterior",
            "parent": "roofing",
            "description": "Plan roof-covering quantity from measured roof area, material packaging and a project-specific waste allowance.",
            "formula": "purchase area = roof surface area × (1 + waste rate)",
            "example": "A 1,500 ft² roof with 12% waste requires planning for about 1,680 ft² of roof-covering area before package rounding.",
            "uses": ["Shingles", "Underlayment", "Roof panels", "Material takeoff checks"],
            "faqs": [
                ("Does this include flashing and ridge cap?", "No. Those items are usually estimated from separate linear measurements and product-specific details."),
                ("Should roof overhangs be included?", "Yes. Measure the actual roof surface or dimensions that include the overhangs when possible."),
                ("Can I use this for metal roofing?", "Area planning can help, but panel lengths, laps, trim and fastening systems need product-specific takeoff rules."),
            ],
        },
        {
            "slug": "deck-board-calculator",
            "title": "Deck Board Calculator",
            "category": "Decks & Fences",
            "parent": "deck",
            "description": "Estimate deck-board rows, linear footage and purchase allowance from deck dimensions, board width and gap.",
            "formula": "board rows ≈ deck width ÷ (board width + gap)",
            "example": "For a 12 ft wide deck, the number of board rows depends on the installed face width plus the planned gap between boards.",
            "uses": ["Wood decking", "Composite decking", "Platform decks", "Board replacement"],
            "faqs": [
                ("Do I use nominal or actual board width?", "Use the actual installed face width, not the nominal lumber name."),
                ("Why include the gap?", "The repeated gap contributes to total deck width and affects the number of board rows."),
                ("Does this include picture-frame borders?", "Not automatically. Borders and breaker boards should be added as separate measured components."),
            ],
        },
        {
            "slug": "fence-post-calculator",
            "title": "Fence Post Calculator",
            "category": "Decks & Fences",
            "parent": "fence",
            "description": "Estimate fence posts and sections from total run length and maximum planning spacing between posts.",
            "formula": "sections = ceil(fence length ÷ target spacing); posts ≈ sections + 1",
            "example": "A 100 ft straight fence planned around 8 ft sections needs at least 13 sections, which means about 14 line/end posts before gates and corners.",
            "uses": ["Privacy fences", "Garden fences", "Straight fence runs", "Early material lists"],
            "faqs": [
                ("Do corners need extra posts?", "Corners, gates, changes in direction and end conditions can change the post count. Treat each fence run separately."),
                ("Is 8 ft spacing always acceptable?", "No. Spacing depends on the fence system, wind, materials, soil and local requirements. Use manufacturer or professional guidance."),
                ("Does this calculate post-hole depth?", "No. Hole diameter and depth are structural and site-specific considerations that require appropriate local guidance."),
            ],
        },
    ]
