from __future__ import annotations


def seo_guides() -> list[dict]:
    return [
        {
            "slug": "insulation-needs-guide",
            "title": "How Much Insulation Do I Need?",
            "category": "Building Planning",
            "topic": "home-improvement",
            "parent": "insulation-calculator",
            "description": "Estimate insulation area and material quantity while checking R-value, coverage, compression and the difference between area and thermal design.",
            "answer": "Insulation quantity starts with the surface area to be covered, but the correct product also depends on the required R-value, cavity depth, product coverage and installation method. Area alone cannot guarantee energy performance.",
            "steps": [
                ("Measure the assembly", "Measure wall, ceiling or floor areas and subtract large openings when the insulation will not cover them."),
                ("Choose the target R-value", "Use the climate zone, building assembly and local energy requirements instead of choosing a thickness by guesswork."),
                ("Check product coverage", "Use the manufacturer's coverage per batt, roll, bag or board and keep the product type visible."),
                ("Plan installation", "Account for cuts, offcuts, compression, air sealing and any required vapor or radiant-control layer."),
            ],
            "formula": "insulation units = net area ÷ coverage per unit",
            "example": "A 900 ft² ceiling using batts that cover 48 ft² per package requires 18.75 packages, so the practical order is rounded up after checking cuts and the specified R-value.",
            "mistakes": "Treating every insulation product as interchangeable, compressing batts into a shallow cavity, ignoring air leakage, and using a quantity estimate as an energy-code design.",
            "faqs": [
                ("Does thicker insulation always work better?", "Only when the assembly, product and installation allow it to achieve the intended performance without compression or moisture problems."),
                ("Should I subtract windows and doors?", "Subtract areas that will not be insulated, then add realistic cutting allowance for the actual installation."),
                ("Can this choose my insulation type?", "No. Use it for quantity planning and confirm product, R-value, moisture control and local requirements."),
            ],
        },
        {
            "slug": "generator-sizing-guide",
            "title": "Generator Sizing: Running Watts and Starting Watts",
            "category": "Electrical Planning",
            "topic": "electrical",
            "parent": "generator-size-calculator",
            "description": "Estimate generator capacity by separating running watts, starting watts, essential circuits and load-management decisions.",
            "answer": "Generator sizing is controlled by the loads that must run together and the highest starting surge from motors, pumps, compressors or refrigerators. A practical plan lists essential loads instead of adding every appliance automatically.",
            "steps": [
                ("List essential loads", "Separate refrigeration, pumps, heating, medical equipment, lighting and communications from optional loads."),
                ("Record running watts", "Use nameplate watts or convert volts and amps consistently for normal operation."),
                ("Add starting demand", "Identify the largest motor or compressor surge and confirm the generator's surge rating."),
                ("Plan load management", "Use transfer equipment and staged starting so large loads do not start at the same moment."),
            ],
            "formula": "minimum capacity must cover simultaneous running watts plus the largest required starting surge",
            "example": "A refrigerator that runs at 700 W but starts at 2,100 W can control the required starting capacity even when the running total looks modest.",
            "mistakes": "Sizing from running watts only, assuming all appliances run at once, ignoring fuel duration, and connecting a portable generator without approved transfer equipment.",
            "faqs": [
                ("Do I add every appliance in the house?", "Usually no. Define essential loads and the combinations that may operate simultaneously."),
                ("Why do motors need extra capacity?", "Their starting current can be several times the running current for a short period."),
                ("Can I wire a generator directly into a panel?", "Do not backfeed a building. Use approved transfer equipment and qualified installation."),
            ],
        },
        {
            "slug": "hvac-airflow-cfm-guide",
            "title": "HVAC Airflow: How to Estimate CFM",
            "category": "HVAC Planning",
            "topic": "hvac",
            "parent": "hvac-airflow-calculator",
            "description": "Estimate preliminary HVAC airflow from room load and temperature difference, then check ducts, filters, registers and equipment data.",
            "answer": "Airflow is commonly estimated from sensible load and the temperature difference between supply and room air. The result is a planning value; actual equipment airflow also depends on static pressure, coil performance, duct design and balancing.",
            "steps": [
                ("Determine the room load", "Use a room-by-room load estimate rather than allocating airflow only by floor area."),
                ("Choose the air temperature difference", "Use a clearly stated supply-to-room temperature difference that matches the equipment context."),
                ("Calculate preliminary CFM", "Use the sensible heat relationship and keep units consistent."),
                ("Verify the distribution", "Check duct friction, filter pressure drop, register throw, return paths and commissioning requirements."),
            ],
            "formula": "CFM ≈ sensible BTU/h ÷ (1.08 × supply-to-room temperature difference in °F)",
            "example": "A room with a 6,480 BTU/h sensible load and a 20°F temperature difference needs about 300 CFM before duct and balancing checks.",
            "mistakes": "Using total load as sensible load, ignoring return air paths, selecting a blower from CFM alone, and assuming every register can deliver the same airflow.",
            "faqs": [
                ("Why is airflow different from BTU capacity?", "Airflow is the delivery rate; capacity depends on air conditions, coil performance and both sensible and latent loads."),
                ("Does a larger duct always fix low airflow?", "It can reduce friction, but fan capacity, transitions, filters, dampers and balancing also matter."),
                ("Can this size my duct system?", "No. Use it as an early airflow check and have the complete duct design reviewed."),
            ],
        },
        {
            "slug": "drywall-material-estimate-guide",
            "title": "How to Estimate Drywall Sheets, Screws and Joint Compound",
            "category": "Interior Renovation",
            "topic": "flooring",
            "parent": "drywall-calculator",
            "description": "Estimate drywall panels and supporting materials from wall and ceiling area while accounting for openings, sheet size and cutting waste.",
            "answer": "Drywall quantity is based on net surface area divided by the coverage of each sheet, then adjusted for layout and waste. Sheet orientation, corners, openings, ceiling height and access can change the practical order.",
            "steps": [
                ("Measure each surface", "Calculate walls and ceilings separately because sheet layout and handling are different."),
                ("Subtract large openings", "Remove doors and windows from net area, but do not assume every small cutout reduces the order."),
                ("Choose sheet size", "Compare 4 × 8 ft, 4 × 10 ft or other available panels with the room dimensions and seam layout."),
                ("Add accessories", "Estimate screws, tape and joint compound from the panel count, finish level and manufacturer guidance."),
            ],
            "formula": "sheet count = net area ÷ sheet area, rounded up with layout allowance",
            "example": "A 720 ft² wall-and-ceiling surface using 32 ft² sheets gives 22.5 sheets before layout and waste, so the practical order starts at 23 and is adjusted for cuts.",
            "mistakes": "Measuring floor area instead of surface area, forgetting ceilings, buying panels without planning seams, and treating joint-compound coverage as universal.",
            "faqs": [
                ("Should drywall waste be higher in small rooms?", "Often yes because corners, openings and short offcuts create more unusable pieces."),
                ("Does the calculator design the framing?", "No. Stud layout, backing, fire rating, moisture resistance and fastening schedules are separate decisions."),
                ("How much joint compound do I need?", "Use the product's coverage and finish level; a smooth Level 5 finish uses more labor and material than a basic finish."),
            ],
        },
        {
            "slug": "paver-base-depth-and-quantity-guide",
            "title": "Paver Base Depth and Material Quantity Guide",
            "category": "Landscaping Planning",
            "topic": "landscaping",
            "parent": "paver-base-calculator",
            "description": "Estimate compacted paver base from patio area and layer depth while separating excavation, base stone, bedding sand and edge restraint.",
            "answer": "Paver base quantity is based on area and the compacted layer depth, but the excavation must allow for base, bedding, pavers and the required drainage. Loose delivery volume is usually greater than the final compacted volume.",
            "steps": [
                ("Map the finished area", "Break irregular patios and paths into rectangles or triangles and add the sections."),
                ("Set the layer depths", "Use the specified compacted base depth for the soil, drainage and expected traffic."),
                ("Convert compacted volume", "Calculate cubic feet or cubic yards, then apply a clearly labeled compaction and handling allowance."),
                ("Plan the build-up", "Include bedding sand, paver thickness, edge restraint, slope and excavation disposal separately."),
            ],
            "formula": "base volume = area × compacted depth; order volume = compacted volume × allowance factor",
            "example": "A 240 ft² patio with a 6 in compacted base needs 120 ft³, or 4.44 yd³, before the supplier-specific allowance for compaction and delivery.",
            "mistakes": "Using paver thickness as base depth, ignoring subgrade drainage, ordering loose material as though it were compacted, and forgetting edge restraints.",
            "faqs": [
                ("How deep should a paver base be?", "It depends on soil, climate, drainage and traffic; use the project specification rather than one universal depth."),
                ("Is bedding sand included in base quantity?", "No. Keep base stone, bedding sand and joint material as separate line items."),
                ("Does the calculator set the patio slope?", "No. Set slope from the drainage plan and confirm elevations before excavation."),
            ],
        },
        {
            "slug": "carpet-flooring-waste-guide",
            "title": "Carpet Area, Seams and Waste: A Planning Guide",
            "category": "Flooring Planning",
            "topic": "flooring",
            "parent": "carpet-calculator",
            "description": "Estimate carpet area while checking roll width, seam placement, room orientation and waste instead of ordering from floor area alone.",
            "answer": "Carpet is sold in fixed roll widths, so the practical order depends on the room layout and seam plan as well as square footage. A small area can still require a large cut when the room dimensions do not fit the roll.",
            "steps": [
                ("Measure every room", "Record the longest dimensions, doorways, closets and transitions rather than relying on a single floor-area number."),
                ("Check roll width", "Compare room dimensions with the product's available width and decide where seams can be placed."),
                ("Plan direction", "Keep pile direction consistent and avoid seams in high-visibility or high-traffic locations where possible."),
                ("Add waste visibly", "Use the cut plan to estimate waste, then include pad, tack strips, thresholds and stair pieces separately."),
            ],
            "formula": "carpet order area = planned cut area × (1 + waste allowance)",
            "example": "A 300 ft² set of rooms may require more than 300 ft² of carpet when the roll width creates long offcuts and a seam plan is needed.",
            "mistakes": "Ordering exact floor area, ignoring roll width, reversing pile direction, and forgetting stairs, closets or transition strips.",
            "faqs": [
                ("Why can carpet waste be high?", "Fixed roll width and seam alignment can create offcuts that cannot be used in the same room."),
                ("Does carpet padding use the same estimate?", "Usually it follows floor area, but seams, stairs and room boundaries should still be checked."),
                ("Can this create an installation diagram?", "It estimates quantity; the installer should finalize the cut and seam plan."),
            ],
        },
        {
            "slug": "window-replacement-cost-guide",
            "title": "Window Replacement Cost: What to Include",
            "category": "Renovation Budgeting",
            "topic": "renovation",
            "parent": "window-cost-calculator",
            "description": "Build a clearer window replacement budget by separating units, labor, trim, disposal, access and opening repairs.",
            "answer": "Window replacement cost is not just the number of units multiplied by a product price. Size, frame material, glazing, installation method, trim, flashing, interior repair, exterior finish, access and disposal can all change the total.",
            "steps": [
                ("Create a window schedule", "List each opening, rough size, operation type, glazing choice and access condition."),
                ("Separate product and labor", "Keep window units, installation, flashing, trim and finish work as separate budget lines."),
                ("Add opening repairs", "Allow for damaged framing, water intrusion, sill repairs and interior or exterior patching when the condition is unknown."),
                ("Compare equivalent quotes", "Check that each quote includes disposal, permits, protection, cleanup and warranty terms before comparing totals."),
            ],
            "formula": "project budget = units + installation + trim and repairs + access + disposal + contingency",
            "example": "Ten windows with the same nominal size can still have different installed costs when some are on upper floors or require framing repair.",
            "mistakes": "Comparing product-only quotes, ignoring rough-opening condition, choosing the lowest unit price without installation scope, and forgetting egress or safety requirements.",
            "faqs": [
                ("Should all windows use the same glass?", "Not necessarily. Orientation, climate, noise, safety and energy goals can change the specification."),
                ("Does replacement always mean a full-frame installation?", "No. Insert and full-frame methods have different scope, cost and opening implications."),
                ("Can a calculator replace a site quote?", "No. Use it to organize a range, then compare written site-specific proposals."),
            ],
        },
        {
            "slug": "fence-post-and-panel-estimate-guide",
            "title": "How to Estimate Fence Posts and Panels",
            "category": "Exterior Planning",
            "topic": "roofing-decks-fences",
            "parent": "fence-post-calculator",
            "description": "Estimate fence posts, panels and sections from length, spacing and gates while accounting for corners, end posts and layout changes.",
            "answer": "Fence post quantity is controlled by the spacing of sections and the special posts at corners, ends and gates. A simple length division is only a starting point because real layouts need posts at every change in direction and opening.",
            "steps": [
                ("Draw the route", "Mark property corners, direction changes, gates, slopes and transitions before dividing the total length."),
                ("Choose section spacing", "Use the panel width or the post spacing required by the fence system."),
                ("Count special posts", "Add end, corner, gate and line posts separately so the material list matches the layout."),
                ("Check materials", "Add panels or rails, concrete, brackets, caps and hardware, then verify local property and setback requirements."),
            ],
            "formula": "line sections ≈ fence run length ÷ panel or post spacing, rounded up; posts include special locations",
            "example": "A 96 ft straight run using 8 ft panels needs 12 sections and typically 13 line-end positions before adding corners or gates.",
            "mistakes": "Dividing total perimeter without a layout, forgetting gate posts, using panel width as a structural span without checking the system, and ignoring slope.",
            "faqs": [
                ("Does every corner need a post?", "Yes, and corners often need a stronger or differently configured post than a line post."),
                ("Do gates use regular posts?", "Usually they need dedicated gate posts sized for the load and hardware."),
                ("Can this calculate footing depth?", "No. Soil, frost, wind and fence height determine post embedment and footing requirements."),
            ],
        },
        {
            "slug": "concrete-block-wall-quantity-guide",
            "title": "How Many Concrete Blocks Do I Need?",
            "category": "Masonry Planning",
            "topic": "concrete",
            "parent": "block-calculator",
            "description": "Estimate concrete masonry units from net wall area, block face dimensions, openings and waste while keeping reinforcement and bond beams separate.",
            "answer": "Concrete block quantity is estimated by dividing the net wall face area by the block face area, then rounding up and adding a visible allowance. Actual block count changes with corners, pilasters, bond beams, cuts and openings.",
            "steps": [
                ("Calculate gross wall area", "Multiply wall length by height for each wall section and add the sections."),
                ("Subtract openings", "Remove doors, windows and large service penetrations from the net block face area."),
                ("Use actual face dimensions", "Include the nominal joint module or the product's stated face size, not only the raw block body size."),
                ("Add layout allowance", "Plan for cuts, breakage, corners and special units, then list reinforcement and grout separately."),
            ],
            "formula": "block count = net wall area ÷ block face area, rounded up with layout allowance",
            "example": "A 240 ft² net wall using a 0.89 ft² block face needs about 270 blocks before corners, cuts and waste are reviewed.",
            "mistakes": "Subtracting openings twice, using raw block dimensions without joints, forgetting corner units, and assuming block count determines structural capacity.",
            "faqs": [
                ("Are all 8 × 8 × 16 blocks the same?", "Face size may be similar, but weight, web configuration, finish and manufacturer details can differ."),
                ("Is mortar included in block count?", "No. Mortar, grout, reinforcement and accessories are separate quantities."),
                ("Can this size a retaining wall?", "No. Retaining-wall stability and drainage require a structural and site-specific design."),
            ],
        },
        {
            "slug": "cement-sand-aggregate-ratio-guide",
            "title": "Cement, Sand and Aggregate Ratio: Quantity Planning",
            "category": "Concrete Planning",
            "topic": "concrete",
            "parent": "cement-calculator",
            "description": "Use cement, sand and aggregate ratios for a transparent material estimate while keeping structural mix design and strength testing separate.",
            "answer": "A ratio calculator can distribute a stated dry-volume assumption among cement, sand and aggregate for a rough material takeoff. It cannot establish a structural concrete mix because strength, workability, moisture, aggregate grading and testing also matter.",
            "steps": [
                ("Define the placed volume", "Start with the finished concrete volume and keep waste or yield assumptions separate."),
                ("State the ratio", "Record whether the ratio is by volume or mass and keep cement, sand and aggregate in the same basis."),
                ("Apply the dry-volume factor", "Use a documented factor to account for voids and packing rather than presenting it as a universal constant."),
                ("Check the mix", "Use approved product or project mix data for structural work, then verify water, admixtures, strength and curing requirements."),
            ],
            "formula": "component share = dry material volume × component ratio ÷ sum of ratio parts",
            "example": "For a 1:2:3 ratio, the six parts are divided into one cement part, two sand parts and three aggregate parts after the stated dry-volume adjustment.",
            "mistakes": "Mixing mass and volume ratios, assuming bag size equals yield, adding water by guesswork, and using a quantity ratio as a structural specification.",
            "faqs": [
                ("Can this guarantee concrete strength?", "No. Strength depends on the approved mix, materials, water-cement ratio, placement and curing."),
                ("Why use a dry-volume factor?", "Dry ingredients contain voids and pack differently from finished concrete; use a documented assumption or product yield."),
                ("Is this suitable for footings or beams?", "Do not use a rough ratio as a substitute for the specified structural mix and professional design."),
            ],
        },
    ]
