def seo_pages():
    return [
        {
            "slug": "concrete-slab-calculator",
            "title": "Concrete Slab Calculator",
            "category": "Concrete & Masonry",
            "parent": "concrete",
            "description": "Estimate concrete volume for a rectangular slab from length, width, thickness and a visible waste allowance.",
            "formula": "cubic yards = length × width × thickness in feet ÷ 27",
            "example": "A 12 × 10 ft slab at 4 in thick is about 1.48 yd³ before adding a project-specific allowance.",
            "uses": ["Patio slabs", "Garage pads", "Walkways", "Small equipment pads"],
            "faqs": [
                ("How thick should a concrete slab be?", "Thickness is project-specific. Use the thickness specified for your actual project, local requirements or professional design rather than a generic default."),
                ("Should I add extra concrete?", "Yes when appropriate for the placement method, subgrade variation and ordering practice. Keep the allowance visible instead of hiding it in the formula."),
                ("Can I calculate an irregular slab?", "Split the slab into simple measurable sections, calculate each section, then add the volumes."),
            ],
        },
        {
            "slug": "concrete-cost-calculator",
            "title": "Concrete Cost Calculator",
            "category": "Concrete & Masonry",
            "parent": "concrete",
            "description": "Estimate concrete material cost from required cubic yards or bags and the current supplier price you actually expect to pay.",
            "formula": "material cost = purchase quantity × unit price",
            "example": "If a project needs 3.5 yd³ and ready-mix is quoted at $165 per yd³, the material subtotal is about $577.50 before delivery, fees and tax.",
            "uses": ["Ready-mix budgeting", "Bagged concrete comparisons", "Patio budgets", "Driveway material planning"],
            "faqs": [
                ("Does the estimate include delivery?", "No. Short-load fees, delivery, pumping, tax and local surcharges should be added from the actual supplier quote."),
                ("Is bagged concrete cheaper than ready-mix?", "It depends on project size, local prices and delivery constraints. Compare the full purchase quantity rather than only the unit price."),
                ("Should I price the exact geometric volume?", "Usually not. First calculate a realistic purchase quantity including the project allowance, then apply supplier pricing."),
            ],
        },
        {
            "slug": "concrete-bag-calculator",
            "title": "Concrete Bag Calculator",
            "category": "Concrete & Masonry",
            "parent": "concrete",
            "description": "Estimate complete 40 lb, 60 lb or 80 lb concrete bags from the volume needed and the actual yield printed on the product package.",
            "formula": "bags = ceil(required volume ÷ yield per bag)",
            "example": "If a product yields 0.60 ft³ per 80 lb bag and the project needs 12 ft³, the geometric requirement is 20 bags before any project allowance.",
            "uses": ["Fence posts", "Small pads", "Steps and repairs", "DIY slab sections"],
            "faqs": [
                ("How much does an 80 lb concrete bag yield?", "Yield varies by product. Use the exact cubic-foot yield printed on the bag or manufacturer data instead of assuming one universal value."),
                ("Why does the bag count round up?", "Concrete bags are purchased as whole packages, so fractional bag requirements must be rounded up."),
                ("Can I mix different bag sizes?", "Yes. Convert each product to its stated yield and build a combination that meets or exceeds the required volume."),
            ],
        },
        {
            "slug": "concrete-patio-calculator",
            "title": "Concrete Patio Calculator",
            "category": "Concrete & Masonry",
            "parent": "concrete",
            "description": "Estimate concrete for a patio slab from measured patio dimensions, slab thickness and a visible ordering allowance.",
            "formula": "patio volume = length × width × thickness",
            "example": "A 16 × 12 ft patio at 4 in thick is about 64 ft³, or 2.37 yd³, before adding the ordering allowance.",
            "uses": ["Backyard patios", "Outdoor seating pads", "Grill pads", "Small courtyard slabs"],
            "faqs": [
                ("Should I subtract openings from a patio slab?", "Subtract only areas that truly will not be poured. Small penetrations may not reduce the order meaningfully."),
                ("How do curves affect the estimate?", "Break curved patios into measurable sections or use a conservative bounding shape, then refine with the actual layout."),
                ("Does this calculate reinforcement?", "No. Reinforcement, joints, base preparation and structural details are separate project decisions."),
            ],
        },
        {
            "slug": "concrete-driveway-calculator",
            "title": "Concrete Driveway Calculator",
            "category": "Concrete & Masonry",
            "parent": "concrete",
            "description": "Estimate concrete driveway volume from driveway dimensions and thickness while keeping waste and ordering assumptions visible.",
            "formula": "driveway cubic yards = length × width × thickness in feet ÷ 27",
            "example": "A 40 × 12 ft driveway at 5 in thick is about 200 ft³, or 7.41 yd³, before allowance.",
            "uses": ["Single-car driveways", "Driveway extensions", "Parking pads", "Replacement slabs"],
            "faqs": [
                ("What driveway thickness should I enter?", "Use the thickness specified for your loading, soil conditions, local requirements and project design rather than relying on a generic value."),
                ("Should the driveway be split into sections?", "Yes when width, thickness or shape changes. Calculate each section separately and add the results."),
                ("Does the calculator include the base layer?", "No. Aggregate base, excavation, reinforcement and finishing are separate quantities and costs."),
            ],
        },
        {
            "slug": "concrete-footing-calculator",
            "title": "Concrete Footing Calculator",
            "category": "Concrete & Masonry",
            "parent": "concrete",
            "description": "Estimate concrete volume for simple rectangular footings from footing length, width, depth and number of identical footings.",
            "formula": "total footing volume = length × width × depth × quantity",
            "example": "Four footings measuring 2 × 2 × 1 ft each require 16 ft³, or about 0.59 yd³, before allowance.",
            "uses": ["Deck footings", "Small wall footings", "Post bases", "Accessory structures"],
            "faqs": [
                ("Can this size a footing for me?", "No. It only estimates material from dimensions you provide. Footing size is a structural and site-specific decision."),
                ("How do I calculate multiple footing sizes?", "Calculate each footing group separately and add the concrete volumes."),
                ("Should form volume be included?", "Use the actual concrete dimensions that will be poured, not the outside dimensions of reusable form components."),
            ],
        },
        {
            "slug": "cubic-yard-calculator",
            "title": "Cubic Yard Calculator",
            "category": "Concrete & Landscape Materials",
            "parent": "concrete",
            "description": "Convert project dimensions into cubic yards for concrete, gravel, soil, mulch and other bulk materials.",
            "formula": "cubic yards = cubic feet ÷ 27",
            "example": "A volume of 81 ft³ equals exactly 3 yd³ because one cubic yard contains 27 cubic feet.",
            "uses": ["Concrete", "Gravel", "Topsoil", "Mulch and fill"],
            "faqs": [
                ("How many cubic feet are in a cubic yard?", "There are 27 cubic feet in one cubic yard."),
                ("Can cubic yards convert directly to tons?", "Not without density. Weight depends on the specific material, gradation and moisture content."),
                ("Should I round cubic yards before ordering?", "Use the supplier’s order increments and the project allowance after calculating the raw geometric volume."),
            ],
        },
        {
            "slug": "concrete-waste-calculator",
            "title": "Concrete Waste Calculator",
            "category": "Concrete & Masonry",
            "parent": "concrete",
            "description": "Apply a transparent concrete waste or ordering allowance to the measured project volume before placing an order.",
            "formula": "purchase volume = measured volume × (1 + allowance rate)",
            "example": "A measured requirement of 5 yd³ with a 7% allowance becomes 5.35 yd³ before supplier order rounding.",
            "uses": ["Ready-mix orders", "Slab projects", "Irregular excavations", "Bagged concrete planning"],
            "faqs": [
                ("Why add a concrete allowance?", "Subgrade variation, measurement error, spillage and placement conditions can make the real requirement exceed ideal geometry."),
                ("Is 10% always necessary?", "No. The appropriate allowance depends on the job. Keeping it editable is more useful than assuming one percentage for every project."),
                ("Do I add waste before bag rounding?", "Yes. Apply the allowance to project volume first, then convert the adjusted volume into complete bags or supplier order increments."),
            ],
        },
        {
            "slug": "how-much-concrete-do-i-need",
            "title": "How Much Concrete Do I Need?",
            "category": "Concrete & Masonry",
            "parent": "concrete",
            "description": "Work out how much concrete a project needs by measuring its real dimensions, converting thickness correctly and adding a visible ordering allowance.",
            "formula": "concrete volume = measured length × width × thickness",
            "example": "For any rectangular pour, convert all dimensions to compatible units first, calculate raw volume, convert to cubic yards, then apply the allowance and purchase rounding.",
            "uses": ["Slabs", "Patios", "Driveways", "Footings and small pours"],
            "faqs": [
                ("What measurements do I need?", "For a rectangular slab, measure length, width and final concrete thickness. Other shapes may need to be split into multiple sections."),
                ("Why is thickness easy to get wrong?", "Thickness is often measured in inches while length and width are in feet. Convert inches to feet before multiplying volume."),
                ("Should I order exactly what the formula says?", "The geometric result is the starting point. Apply the allowance and supplier order increment appropriate to the real project."),
            ],
        },
    ]
