from __future__ import annotations


def seo_guides() -> list[dict]:
    return [
        {
            "slug": "concrete-slab-bag-vs-ready-mix-guide",
            "title": "Concrete Slab: Bags or Ready-Mix?",
            "category": "Concrete & Masonry",
            "topic": "concrete",
            "parent": "concrete-slab-calculator",
            "description": "Compare bagged concrete with ready-mix for a slab by volume, labor, delivery, waste and practical ordering limits.",
            "answer": "For most slabs that need a continuous pour or more than a small DIY volume, ready-mix is usually the better choice because it is faster and more consistent. Bagged concrete is usually better for a small, accessible, non-structural slab when you have enough labor and mixing time. Calculate the slab volume first, then compare delivered material, labor, access, placement, finishing and cleanup costs.",
            "steps": [
                ("Measure the slab", "Calculate each rectangular section from length, width and designed thickness."),
                ("Convert to cubic yards", "Divide cubic feet by 27 so the quantity can be compared with ready-mix ordering units."),
                ("Estimate bag count", "Divide the required volume by the yield printed on the exact bag, then round up."),
                ("Compare the whole job", "Include mixing labor, water, delivery, placement speed, waste, finishing and cleanup."),
            ],
            "formula": "bag count = required volume ÷ yield per bag; ready-mix order = required cubic yards plus supplier allowance",
            "example": "A 10 ft × 10 ft slab at 4 in is about 1.23 yd³ before allowance. The bag count depends on the exact bag yield, while a ready-mix order must also account for minimum truck quantity and access.",
            "mistakes": "Using the bag weight as its volume, comparing only advertised material prices, forgetting the finishing window, and ordering a structural slab without confirming its design.",
            "faqs": [
                ("When is ready-mix usually easier?", "Larger pours and pours that need a continuous placement window often favor ready-mix, subject to truck access and local supply."),
                ("Can I mix a slab in bags?", "Small non-structural projects may be practical, but labor, consistency and placement time become important as volume grows."),
                ("Does this choose slab thickness?", "No. Thickness, reinforcement, joints and subgrade design must come from the project requirements."),
            ],
        },
        {
            "slug": "rebar-grid-quantity-planning-guide",
            "title": "How to Estimate Rebar for a Slab Grid",
            "category": "Concrete & Masonry",
            "topic": "concrete",
            "parent": "rebar-calculator",
            "description": "Estimate slab rebar bars, grid intersections, total length and stock bars from spacing, edge clearance and allowance.",
            "answer": "Use two separate bar counts—one in each direction—to estimate a slab rebar grid; do not estimate it from slab area alone. Count bars across each usable span, multiply each count by its run length, add laps or cutting allowance, and round to purchasable stock lengths. Bar size, spacing and structural placement still come from the project design.",
            "steps": [
                ("Confirm the layout", "Use the specified bar size, spacing, edge clearance, cover and lap rules from the plans."),
                ("Count each direction", "Calculate bars across the usable width and usable length separately, including the end bar where required."),
                ("Calculate total length", "Multiply bars in each direction by their run length and add both directions."),
                ("Round the purchase", "Apply a visible cutting or lap allowance, then round to stock bar quantities."),
            ],
            "formula": "bars across = ceil(usable span ÷ spacing) + 1; total length = direction A + direction B",
            "example": "A 20 ft × 12 ft slab at 12 in spacing with 3 in edge clearance creates two bar counts, not one area-only estimate. The final stock-bar count changes with the selected stock length and allowance.",
            "mistakes": "Dividing slab area by spacing, forgetting the second direction, ignoring edge clearance, and treating a quantity tool as structural reinforcement design.",
            "faqs": [
                ("Does the calculator tell me which bar size to use?", "No. Bar size and spacing must come from the structural drawings or qualified design."),
                ("Why add a lap allowance?", "Cutting, laps, bends and unusable ends can make purchase length greater than the net grid length."),
                ("Are intersections the same as ties?", "Intersections show grid crossings; tie count and tying method are separate estimating decisions."),
            ],
        },
        {
            "slug": "concrete-patio-cost-breakdown-guide",
            "title": "Concrete Patio Cost Breakdown Guide",
            "category": "Concrete & Masonry",
            "topic": "concrete",
            "parent": "concrete-patio-calculator",
            "description": "Build a concrete patio estimate by separating concrete volume, base, reinforcement, forming, finishing, access and site work.",
            "answer": "A concrete patio budget is not just the concrete price. Separate concrete volume, demolition, excavation, base preparation, forms, reinforcement, finishing, joints, delivery, access and labor so the estimate reflects the installed job rather than one material line.",
            "steps": [
                ("Measure the footprint", "Split the patio, steps, thickened edges and irregular sections into simple shapes."),
                ("Calculate concrete", "Use the designed thickness and add a separate ordering allowance."),
                ("List preparation work", "Include excavation, disposal, compacted base, drainage, forms and reinforcement where specified."),
                ("Compare complete quotes", "Check placement, finishing, curing, joints, cleanup, permits and access restrictions."),
            ],
            "formula": "installed patio budget = concrete + base + forms + reinforcement + labor + access + disposal + contingency",
            "example": "Two patios with the same 300 ft² area can have different installed costs if one has easy truck access and the other needs pumping, demolition or extensive base repair.",
            "mistakes": "Multiplying area by a local price without defining scope, forgetting the base, and treating a material calculator as a contractor quotation.",
            "faqs": [
                ("Does patio size determine most of the cost?", "It affects material quantity, but access, preparation, finishing and labor can dominate smaller projects."),
                ("Should old concrete removal be separate?", "Yes. Demolition, hauling and disposal should be visible rather than hidden in one rate."),
                ("Is reinforcement included automatically?", "No. Use the project design to identify reinforcement and calculate it separately."),
            ],
        },
        {
            "slug": "flooring-box-coverage-and-waste-guide",
            "title": "How Many Flooring Boxes Do I Need?",
            "category": "Flooring & Tile",
            "topic": "flooring",
            "parent": "flooring-box-calculator",
            "description": "Calculate flooring boxes from measured area, carton coverage, layout waste and whole-box rounding.",
            "answer": "To find flooring boxes, multiply the net floor area by one plus the waste allowance, divide by the carton coverage, and round up to whole boxes. Measure every installation area first, then use the exact coverage printed on the product carton.",
            "steps": [
                ("Measure the floor", "Calculate each room and add only areas that will receive the same flooring."),
                ("Subtract fixed exclusions", "Remove permanent cabinets or untiled areas, but do not subtract movable furniture."),
                ("Choose the waste allowance", "Use more allowance for angled layouts, patterns, many rooms, stairs or difficult cuts."),
                ("Round cartons", "Divide by the actual carton coverage and always purchase complete cartons."),
            ],
            "formula": "boxes = ceil((net flooring area × (1 + waste percentage)) ÷ carton coverage)",
            "example": "A 420 ft² layout with 8% waste needs 453.6 ft² of planned coverage. If each carton covers 23.5 ft², the order rounds up to 20 cartons.",
            "mistakes": "Using room length only, rounding each room before adding, trusting nominal coverage instead of the carton label, and forgetting transitions or stairs.",
            "faqs": [
                ("What waste percentage should I use?", "The layout, product and installer cut plan determine it; simple rectangles usually need less than complex patterns."),
                ("Can leftover flooring be returned?", "Return policies vary, so confirm the supplier policy before intentionally over-ordering."),
                ("Do I include closets?", "Include closets when they receive the same flooring and are part of the installation scope."),
            ],
        },
        {
            "slug": "room-paint-two-coats-guide",
            "title": "How Much Paint for Two Coats in a Room?",
            "category": "Paint & Finishes",
            "topic": "paint",
            "parent": "room-paint-calculator",
            "description": "Estimate room paint for walls and ceilings by measuring surface area, subtracting openings and multiplying by coats.",
            "answer": "For two coats, multiply the paintable wall or ceiling area by two, divide by the product's coverage per gallon, and round up to whole containers. Subtract major openings and account for texture, primer, product coverage and any separate ceiling finish.",
            "steps": [
                ("Measure the walls", "Add each wall length and multiply by wall height, or calculate each wall separately."),
                ("Subtract major openings", "Remove large doors and windows while keeping small cuts and texture allowance realistic."),
                ("Add the ceiling separately", "Ceiling paint can have a different product and coverage rate from wall paint."),
                ("Multiply by coats", "Apply two coats only when the finish plan calls for two coats, then round gallons up."),
            ],
            "formula": "gallons = (paintable area × number of coats) ÷ coverage per gallon",
            "example": "A room with 500 ft² of paintable wall area, two coats and 350 ft² per gallon has a theoretical need of 2.86 gallons before texture, primer and package rounding.",
            "mistakes": "Using floor area as wall area, forgetting the ceiling, assuming all surfaces cover like smooth drywall, and mixing primer coverage with finish coverage.",
            "faqs": [
                ("Do dark colors need two coats?", "Often they can, but coverage depends on the product, base color, surface and application method."),
                ("Should primer be counted as paint?", "Treat primer as a separate product and coat when the project requires it."),
                ("Do I subtract every window?", "Subtract meaningful openings, but keep a realistic allowance for edges, texture and touch-up."),
            ],
        },
        {
            "slug": "mulch-bag-coverage-by-depth-guide",
            "title": "How Many Bags of Mulch Do I Need?",
            "category": "Landscaping",
            "topic": "landscaping",
            "parent": "mulch-calculator",
            "description": "Calculate mulch bags from landscape area, installed depth, bag volume and practical settling allowance.",
            "answer": "To estimate mulch bags, multiply the bed area by the desired depth in feet, divide the resulting cubic feet by the volume printed on each bag, and round up. Bag coverage changes with bag size, depth, settling and the actual landscape layout.",
            "steps": [
                ("Measure the bed", "Split curved or irregular beds into simple sections and add their areas."),
                ("Set the depth", "Choose a depth appropriate for the plants and existing conditions instead of copying one universal number."),
                ("Calculate cubic feet", "Convert the depth from inches to feet before multiplying by area."),
                ("Convert to bags", "Divide by the labeled bag volume and round to whole bags."),
            ],
            "formula": "mulch volume(ft³) = area(ft²) × depth(ft); bags = volume ÷ bag volume",
            "example": "A 100 ft² bed at 3 in needs 25 ft³ of mulch before settling and coverage adjustments. A 2 ft³ bag would require 13 bags after rounding.",
            "mistakes": "Using bag weight as volume, entering 3 instead of 3/12 for a 3 in depth, and applying the same depth around every plant and tree.",
            "faqs": [
                ("How deep should mulch be?", "Use plant, drainage and landscape guidance; excessive depth can create moisture and root problems."),
                ("Why does bag coverage differ?", "Bags have different labeled volumes and the material settles differently."),
                ("Can I calculate cubic yards instead?", "Yes. Divide cubic feet by 27 and compare the result with bulk delivery quantities."),
            ],
        },
        {
            "slug": "roof-area-pitch-measurement-guide",
            "title": "How to Calculate Roof Area with Pitch",
            "category": "Roofing, Decks & Fences",
            "topic": "roofing-decks-fences",
            "parent": "roof-area-calculator",
            "description": "Estimate roof surface area by separating plan dimensions, pitch factors, roof planes and waste-producing features.",
            "answer": "To estimate roof area with pitch, multiply each horizontal roof-plane area by its correct pitch factor, add all roof planes, and then allow for waste and accessories. The sloped surface is larger than the horizontal footprint, especially on complex roofs with hips, valleys, dormers and penetrations.",
            "steps": [
                ("Map each plane", "Treat gables, hips, porches and additions as separate roof sections."),
                ("Measure the plan area", "Use horizontal length and width for each section when the factor method applies."),
                ("Apply pitch", "Use the correct rise-to-run factor or calculate the sloped length from the roof geometry."),
                ("Add ordering items", "Convert area to squares or bundles using the product label and include starter, ridge and flashing materials separately."),
            ],
            "formula": "sloped roof area = horizontal plan area × pitch factor",
            "example": "A 1,500 ft² horizontal roof footprint with a 6:12 pitch uses a factor of about 1.118, giving roughly 1,677 ft² of sloped surface before waste and accessories.",
            "mistakes": "Using floor area without pitch, applying one factor to every roof plane, ignoring porches and additions, and measuring an unsafe roof without proper equipment.",
            "faqs": [
                ("What is a roofing square?", "One roofing square is 100 ft² of roof surface, but bundle coverage depends on the specific shingle."),
                ("Do hips and valleys change area?", "They affect cuts and accessory materials and may affect the measured geometry of complex planes."),
                ("Can I measure a roof from the ground?", "Often you can estimate from plans or ground dimensions, but never access a roof unsafely."),
            ],
        },
        {
            "slug": "deck-board-linear-feet-guide",
            "title": "How to Estimate Deck Board Linear Feet",
            "category": "Roofing, Decks & Fences",
            "topic": "roofing-decks-fences",
            "parent": "deck-board-calculator",
            "description": "Estimate deck board count and linear feet from deck dimensions, board face width, gap, stock length and waste.",
            "answer": "To estimate deck boards, divide each deck width by the board face width plus the installation gap, round the row count up, and multiply by the board run. Then add separate quantities for stairs, borders, picture framing, stock-length cuts and realistic waste.",
            "steps": [
                ("Measure each zone", "Separate the main field, stairs, landings, borders and picture-frame sections."),
                ("Use actual module width", "Combine board face width and the required gap to calculate rows."),
                ("Calculate linear footage", "Multiply row count by the run length and add separate zones."),
                ("Review stock lengths", "Round to available board lengths and keep reusable offcuts separate from waste."),
            ],
            "formula": "rows = ceil(deck width ÷ (board face width + gap)); linear feet = rows × board run",
            "example": "A 12 ft wide deck using a 5.5 in face width and 1/8 in gap needs about 26 rows before borders, stairs and waste are reviewed.",
            "mistakes": "Using nominal board width, ignoring the gap, treating all offcuts as reusable, and forgetting stairs or picture-frame borders.",
            "faqs": [
                ("Does composite decking use the same gap?", "Follow the selected manufacturer's installation instructions because spacing can change with temperature and product type."),
                ("Should stairs be calculated separately?", "Yes. Stair treads and risers create different lengths and cuts."),
                ("Does this size the joists?", "No. Framing, spans, fasteners and ledger details require separate structural planning."),
            ],
        },
        {
            "slug": "fence-gate-post-estimate-guide",
            "title": "How Many Fence Posts Does a Gate Need?",
            "category": "Roofing, Decks & Fences",
            "topic": "roofing-decks-fences",
            "parent": "fence-post-calculator",
            "description": "Estimate line, corner and gate posts for a fence layout while keeping gate loads and footing requirements separate.",
            "answer": "Plan on two dedicated gate posts for a typical gate opening, in addition to line, end and corner posts. Gate width, hardware, gate weight, wind exposure and soil conditions determine whether those posts and their footings need a stronger design.",
            "steps": [
                ("Draw the fence route", "Mark every end, corner, direction change, gate and change in height."),
                ("Count ordinary sections", "Divide each straight run by the selected panel or post spacing and round up."),
                ("Add gate posts", "Count one post on each side of every gate opening, then check whether the system needs reinforced posts."),
                ("Plan footings", "Confirm embedment, concrete and local requirements from the fence system and site conditions."),
            ],
            "formula": "total posts = line posts + corner/end posts + two gate posts per gate opening",
            "example": "A straight 96 ft run using 8 ft panels needs 12 sections and 13 end positions. A single gate adds two dedicated gate posts before corner and footing adjustments.",
            "mistakes": "Subtracting the gate but forgetting its two posts, using regular line posts for a heavy gate, and estimating footing depth from fence length alone.",
            "faqs": [
                ("Does a double gate need four posts?", "Usually it needs two posts at the outer sides and a center condition determined by the gate system; confirm the manufacturer's layout."),
                ("Are gate posts the same as line posts?", "Often they are stronger or larger because they carry hinges, latch forces and gate movement."),
                ("Can this calculate wind loading?", "No. Wind, height, material and local requirements may require a separate design review."),
            ],
        },
        {
            "slug": "concrete-driveway-gravel-base-guide",
            "title": "How Much Gravel Base for a Concrete Driveway?",
            "category": "Concrete & Masonry",
            "topic": "concrete",
            "parent": "concrete-driveway-calculator",
            "description": "Estimate driveway gravel base volume from area and compacted depth while separating excavation, drainage and concrete quantities.",
            "answer": "To estimate driveway gravel base, multiply the driveway area by the specified compacted base depth, convert the result to cubic yards, and then confirm the supplier's loose-volume allowance. The correct depth depends on soil, drainage, climate and expected vehicle loads.",
            "steps": [
                ("Measure the driveway", "Calculate the main slab, apron, widening and turning areas separately."),
                ("Confirm base depth", "Use the project specification or qualified site guidance rather than one generic depth."),
                ("Calculate compacted volume", "Multiply area by depth and convert cubic feet to cubic yards."),
                ("Check delivery allowance", "Ask the supplier how compaction, moisture and truck volume are represented before ordering."),
            ],
            "formula": "base volume(ft³) = area(ft²) × compacted depth(ft); cubic yards = ft³ ÷ 27",
            "example": "A 600 ft² driveway with a 6 in compacted base needs 300 ft³, or 11.11 yd³, before the supplier-specific allowance and any apron or widening.",
            "mistakes": "Using concrete thickness as base depth, forgetting the apron, ordering compacted volume without an allowance, and ignoring drainage or weak subgrade.",
            "faqs": [
                ("Is gravel base the same as crushed concrete?", "Materials and gradations differ, so use the supplier's product description and compaction guidance."),
                ("Does the calculator design driveway base depth?", "No. Base design depends on soil, drainage, climate and traffic."),
                ("Should I calculate concrete separately?", "Yes. Keep base aggregate, concrete, reinforcement and finishing as separate quantities."),
            ],
        },
    ]
