from __future__ import annotations

def seo_guides() -> list[dict]:
    pages=[
        ("home-improvement-budget-guide","How to Build a Home Improvement Budget","Renovation & Remodeling","flooring","home-improvement-cost-calculator","Create an early home improvement budget by separating materials, labor, permits and project uncertainty.","Define the scope, list materials, estimate labor and keep permits, disposal and site conditions visible."),
        ("renovation-cost-per-square-foot-guide","Renovation Cost per Square Foot: How to Use It","Renovation & Remodeling","flooring","renovation-cost-calculator","Use cost-per-square-foot figures as an early comparison tool without treating them as a final quote.","Square-foot ranges are only useful when scope, finish level, location and labor assumptions are stated."),
        ("kitchen-countertop-measurement-guide","How to Measure Countertops","Renovation & Remodeling","flooring","kitchen-remodel-cost-calculator","Estimate countertop area from cabinet runs, depth, cutouts and edge details before requesting quotes.","Measure each run separately, include backsplash where applicable and leave fabrication cutouts visible."),
        ("bathroom-tile-wall-area-guide","How to Calculate Bathroom Wall Tile","Flooring & Tile","flooring","bathroom-tile-calculator","Calculate bathroom wall tile from wall lengths, tile height, openings and shower layout.","Measure shower walls, vanity walls and backsplash areas separately before adding waste."),
        ("concrete-retaining-wall-material-guide","Concrete Retaining Wall Material Planning","Concrete & Masonry","concrete","concrete-volume-calculator","Plan concrete quantities for simple retaining-wall components while keeping structural design separate.","Estimate each footing, wall section and cap separately; structural reinforcement and drainage need qualified design."),
        ("sand-base-calculator-guide","How to Calculate Sand for a Base","Landscaping","landscaping","sand-calculator","Estimate sand volume for paver bases, leveling and masonry planning from area and depth.","Use the specified installed depth and keep base sand separate from bedding, joint or fill sand."),
        ("paver-patio-material-guide","How to Calculate Pavers for a Patio","Landscaping","landscaping","paver-calculator","Estimate paver count from patio area, paver dimensions, pattern and cutting allowance.","Calculate net area, convert each paver to square feet, add layout waste and round to pallets or packages."),
        ("roof-replacement-cost-guide","How to Build a Roof Replacement Budget","Roofing, Decks & Fences","roofing-decks-fences","roofing-material-calculator","Separate shingles, underlayment, flashing, tear-off, disposal, labor and roof complexity in an early roof budget.","Roof area alone is not enough; pitch, access, layers, valleys and penetrations affect the project."),
        ("fence-cost-per-foot-guide","Fence Cost per Linear Foot: What Changes It","Roofing, Decks & Fences","roofing-decks-fences","fence","Compare fence budgets by separating panels, posts, gates, concrete, labor and terrain.","Linear-foot figures are useful only when material, height, gate count and site conditions are comparable."),
        ("deck-railing-quantity-guide","How to Calculate Deck Railing","Roofing, Decks & Fences","roofing-decks-fences","deck","Estimate deck railing length from exposed edges, stairs, posts and local safety requirements.","Measure every exposed edge, subtract openings and treat stair railing as a separate component."),
    ]
    result=[]
    for slug,title,category,topic,parent,description,answer in pages:
        result.append({"slug":slug,"title":title,"category":category,"topic":topic,"parent":parent,"description":description,"answer":answer,"steps":[("Define the scope.","Separate surfaces, materials and site work."),("Measure the project.","Use actual dimensions and split complex shapes."),("Apply product assumptions.","Use package coverage, unit price or design specification."),("Review the estimate.","Confirm local rules, supplier information and professional requirements.")],"formula":"early planning estimate = measured quantity × product or project assumption","example":"A transparent estimate shows measured quantity, allowance, package rounding and labor as separate fields.","mistakes":"Do not present an early planning range as a quote or use one generic price without explaining scope and assumptions.","faqs":[("Is this a contractor quote?","No. It is an early planning resource before local quotes."),("Why do prices vary?","Product selection, location, access, labor, site conditions and scope all change the result."),("When should I ask a professional?","Ask for qualified guidance when the work affects structure, utilities, waterproofing, roofing safety or code compliance.")]})
    return result
