from __future__ import annotations


def seo_guides() -> list[dict]:
    return [
        {
            "slug": "how-to-read-concrete-bag-yield-label",
            "title": "How to Read a Concrete Bag Yield Label",
            "category": "Concrete & Masonry",
            "topic": "concrete",
            "parent": "concrete-bag-calculator",
            "description": "Use the yield printed on a concrete bag to convert slab volume into a realistic purchase quantity without confusing weight and coverage.",
            "answer": "Concrete bag count should be based on the yield printed on the exact product, not the bag weight alone. Calculate the project volume first, divide by the labeled yield per bag, then add an explicit allowance and round up to complete bags. Different products and bag sizes can produce very different counts.",
            "steps": [
                ("Calculate project volume", "Use the measured length, width and thickness, then convert the result to the same volume unit used by the label."),
                ("Find labeled yield", "Read the current bag instructions for yield per 80 lb, 60 lb or other package size."),
                ("Add project allowance", "Keep waste, spillage, uneven subgrade and placement loss visible instead of hiding them in the formula."),
                ("Round the order", "Always round up to complete bags and confirm water, mixing and curing instructions."),
            ],
            "formula": "bags = (project volume × (1 + allowance)) ÷ labeled yield per bag",
            "example": "A 10 ft × 10 ft slab at 4 in is about 1.23 yd³ before allowance. The correct bag count depends on the yield printed on the selected product, not simply on whether the bag weighs 80 lb.",
            "mistakes": "Using pounds as if they were cubic feet, copying a yield from another product, rounding down, and ignoring the time and labor needed to mix and place the bags.",
            "faqs": [
                ("Does an 80 lb bag always cover the same area?", "No. Yield varies by product formulation and the volume printed on the current label is the value to use."),
                ("Should I use the bag weight in the formula?", "Use the labeled yield for volume. Weight can help compare products but is not a substitute for yield."),
                ("Should I buy extra bags?", "Use a visible allowance appropriate to the project and confirm return policies before ordering excess material."),
            ],
        },
        {
            "slug": "concrete-ordering-delivery-minimum-guide",
            "title": "How to Order Ready-Mix Concrete Without Guessing",
            "category": "Concrete & Masonry",
            "topic": "concrete",
            "parent": "concrete",
            "description": "Prepare a ready-mix concrete order by checking volume, minimum truck loads, access, placement speed, mix specification and finishing needs.",
            "answer": "A ready-mix order needs more than a cubic-yard calculation. Measure the actual pour, add a controlled ordering allowance, then confirm the supplier minimum, mix specification, delivery window, truck access, pump or chute needs, placement crew and finishing plan. The right order is the quantity that can be placed and finished safely within the delivery window.",
            "steps": [
                ("Measure the pour", "Split slabs, footings, thickened edges and separate pours into simple sections."),
                ("Calculate order volume", "Convert the net volume to cubic yards and keep the allowance separate."),
                ("Check supplier limits", "Ask about minimum order, truck capacity, short-load charges, delivery fees and available mix designs."),
                ("Prepare placement", "Confirm access, forms, reinforcement, labor, tools, weather protection and finishing timing before the truck arrives."),
            ],
            "formula": "ready-mix order = measured volume in yd³ + controlled ordering allowance",
            "example": "A 12 ft × 20 ft slab at 4 in is about 2.96 yd³ before allowance. The final order should be compared with the supplier's minimum load and the actual placement conditions.",
            "mistakes": "Ordering from floor area alone, forgetting thickened sections, comparing only the per-yard price, and scheduling delivery before the site and finishing crew are ready.",
            "faqs": [
                ("What should I ask the concrete supplier?", "Ask about mix specification, minimum load, delivery window, access, short-load fees, slump guidance and any local ordering requirements."),
                ("Is the calculator a concrete order quote?", "No. It is a planning estimate; the supplier confirms availability, mix, delivery and final quantity."),
                ("Why can a small order cost more per yard?", "Minimum loads, short-load charges, delivery distance and access can change the effective cost."),
            ],
        },
        {
            "slug": "flooring-carton-coverage-ordering-guide",
            "title": "How to Use Flooring Carton Coverage Before You Buy",
            "category": "Flooring & Tile",
            "topic": "flooring",
            "parent": "flooring-box-calculator",
            "description": "Turn measured flooring area into complete cartons by checking labeled coverage, layout waste, transitions, stairs and return policies.",
            "answer": "Use the exact carton coverage printed on the selected flooring, not a generic listing estimate. Measure the installation area, subtract only fixed exclusions, add a layout-specific waste allowance, divide by carton coverage and round up. Then check whether transitions, stairs, pattern matching and future repairs require additional material.",
            "steps": [
                ("Measure installation zones", "Record rooms, closets, hallways, stairs and transition areas separately when the product or layout changes."),
                ("Read the carton", "Use the current product label for square-foot coverage and plank or tile dimensions."),
                ("Set waste intentionally", "Complex cuts, diagonal layouts, patterns and multiple rooms usually need more allowance than one simple rectangle."),
                ("Order complete cartons", "Round up, then check return rules and keep a small labeled reserve for future repairs."),
            ],
            "formula": "cartons = ceil((net area × (1 + layout waste)) ÷ labeled carton coverage)",
            "example": "A 520 ft² installation with 10% layout allowance needs 572 ft² of planned coverage. At 23.5 ft² per carton, the purchase rounds to 25 cartons.",
            "mistakes": "Using nominal plank dimensions, subtracting movable furniture, rounding every room before adding, and assuming leftover cartons are always returnable.",
            "faqs": [
                ("Should I use the product listing or carton label?", "Use the current carton or manufacturer specification for the selected product and batch when available."),
                ("Do stairs need extra flooring?", "Yes. Treads, risers, nosing and cut direction can require separate quantities."),
                ("How much waste should I add?", "Use the installer cut plan, room shape, pattern and product return policy rather than one universal percentage."),
            ],
        },
        {
            "slug": "paint-primer-vs-finish-quantity-guide",
            "title": "Primer vs. Paint: How Much of Each Do You Need?",
            "category": "Paint & Finishes",
            "topic": "paint",
            "parent": "room-paint-calculator",
            "description": "Separate primer and finish-paint quantities by surface, coats, openings, product coverage and surface condition.",
            "answer": "Primer and finish paint should be estimated as separate products because their coverage, number of coats and purpose can differ. Calculate the paintable surface area, subtract major openings, multiply by the planned primer or finish coats, divide by each product's coverage and round containers up.",
            "steps": [
                ("Map the surfaces", "Separate walls, ceilings, trim and special surfaces when they use different products."),
                ("Subtract meaningful openings", "Remove large doors and windows while keeping edges, texture and touch-up realistic."),
                ("Estimate primer", "Use the primer label and the number of primer coats required for the surface condition."),
                ("Estimate finish paint", "Use the finish product coverage and coat plan separately, then round each container quantity."),
            ],
            "formula": "containers = ceil((paintable area × planned coats) ÷ product coverage per container)",
            "example": "A 450 ft² wall area with one primer coat at 300 ft² per gallon needs 1.5 gallons before rounding. Two finish coats at 350 ft² per gallon need 2.57 gallons before rounding; the products should not be combined into one number.",
            "mistakes": "Using floor area as wall area, assuming primer and finish have identical coverage, forgetting porous or textured surfaces, and mixing ceiling paint into the wall estimate.",
            "faqs": [
                ("Do I always need primer?", "Not always. Surface condition, color change, repairs and the selected paint system determine whether primer is needed."),
                ("Can I use the same coverage for primer and paint?", "Only if the current product labels support that assumption; verify each product separately."),
                ("Should I include ceilings and trim?", "Include them as separate surfaces when they are part of the job and use the relevant product coverage."),
            ],
        },
        {
            "slug": "driveway-gravel-delivery-tonnage-guide",
            "title": "Driveway Gravel: Cubic Yards, Tons and Delivery",
            "category": "Landscaping",
            "topic": "landscaping",
            "parent": "gravel",
            "description": "Convert driveway gravel volume into estimated tons while checking compacted depth, density, delivery minimums and spreading conditions.",
            "answer": "A driveway gravel order starts with area and the specified compacted depth, then converts volume using the actual material density. The delivered quantity may be different because loose gravel compacts, settles and varies by moisture and source. Confirm the supplier's tonnage conversion, delivery minimums and spreading plan before ordering.",
            "steps": [
                ("Measure the driveway", "Split parking bays, aprons and irregular sections into simple areas."),
                ("Use compacted depth", "Enter the specified installed depth and convert inches to feet before calculating volume."),
                ("Convert with density", "Use the supplier's density or tonnage conversion for the selected gravel type."),
                ("Check delivery", "Ask about truck capacity, minimum loads, access, dumping location, spreading and compaction."),
            ],
            "formula": "volume(ft³) = area(ft²) × depth(ft); weight = volume × material density",
            "example": "A 24 ft × 40 ft driveway at 4 in has 320 ft³, or about 11.85 yd³, before supplier-specific compaction and delivery adjustments. The tonnage depends on the selected gravel density.",
            "mistakes": "Using loose depth as compacted depth, assuming every gravel type weighs the same, ordering by truckload without measuring, and forgetting the driveway edge or apron.",
            "faqs": [
                ("How many tons are in a cubic yard of gravel?", "It varies by material, moisture and source. Use the supplier's current density or conversion."),
                ("Should I calculate compacted or loose gravel?", "Start with the specified compacted depth, then ask the supplier how much loose material is needed to achieve it."),
                ("Does the calculator include delivery?", "No. Delivery, spreading, access and compaction should be confirmed separately."),
            ],
        },
        {
            "slug": "roofing-accessory-order-checklist",
            "title": "Roofing Order Checklist Beyond Shingles",
            "category": "Roofing, Decks & Fences",
            "topic": "roofing-decks-fences",
            "parent": "roofing",
            "description": "Use roof area and shingle bundle estimates while separately checking underlayment, starter, ridge, flashing, ventilation and fasteners.",
            "answer": "A roofing estimate is incomplete if it only counts field shingles. Calculate each roof plane, convert the surface area to squares or bundles using the product label, then make separate line items for starter shingles, ridge caps, underlayment, ice and water protection where required, flashing, vents, drip edge and fasteners.",
            "steps": [
                ("Calculate roof planes", "Measure or estimate each plane with its pitch and include additions, porches, hips and valleys."),
                ("Convert field coverage", "Use the exact bundle coverage and apply waste based on roof complexity and cut pattern."),
                ("List accessories", "Measure eaves, rakes, ridges, valleys, penetrations and flashing locations separately."),
                ("Confirm installation requirements", "Use the selected manufacturer's instructions and local requirements for underlayment, ventilation and fastening."),
            ],
            "formula": "field shingles = ceil((total sloped roof area × (1 + waste)) ÷ bundle coverage)",
            "example": "A 2,000 ft² sloped roof with 10% waste needs 2,200 ft² of planned field coverage, or 22 squares. Starter, ridge and flashing quantities still need separate measurements.",
            "mistakes": "Treating squares as bundles, applying one waste rate to every roof, forgetting starter or ridge materials, and accessing the roof without proper safety equipment.",
            "faqs": [
                ("Are roofing squares the same as bundles?", "No. A square is 100 ft² of roof surface; bundle count depends on the selected shingle coverage."),
                ("What accessories are commonly missed?", "Starter, ridge caps, underlayment, flashing, drip edge, ventilation and fasteners are commonly separate line items."),
                ("Does this replace a roofing inspection?", "No. Roof condition, deck condition, flashing details and local requirements need qualified review."),
            ],
        },
        {
            "slug": "rebar-stock-length-cutting-allowance-guide",
            "title": "Rebar Stock Length and Cutting Allowance Guide",
            "category": "Concrete & Masonry",
            "topic": "concrete",
            "parent": "rebar-calculator",
            "description": "Turn a rebar grid's net length into a purchase estimate by checking laps, bends, stock lengths, cuts and structural drawings.",
            "answer": "Net rebar grid length is not the same as the number of stock bars to buy. Count each direction from the actual layout, add required laps, hooks, bends and cutting allowance, then map the total to the stock lengths available from the supplier. Bar size, spacing, cover and lap requirements must come from the structural design.",
            "steps": [
                ("Confirm the design", "Use the specified bar size, spacing, cover, development and lap requirements."),
                ("Count both directions", "Calculate usable runs separately and include edge bars and any additional perimeter or opening bars."),
                ("Plan the cuts", "Match the required pieces to actual stock lengths rather than dividing total feet by one assumed length."),
                ("Round the purchase", "Add only a visible cutting and handling allowance, then confirm bundles and delivery with the supplier."),
            ],
            "formula": "purchase bars = stock-length cutting plan for net runs + required laps, bends and allowance",
            "example": "A slab can have the same net grid footage but need a different purchase quantity when stock lengths, openings, laps and cut reuse change. A bar-foot total alone is not a cutting plan.",
            "mistakes": "Dividing total feet by a stock length without planning cuts, ignoring laps, counting only one grid direction, and using a quantity estimate as structural design.",
            "faqs": [
                ("Does rebar size change the number of bars?", "Spacing and layout determine the count; bar size affects weight, handling and structural design requirements."),
                ("Should laps be included?", "Use the lap requirements in the project design and keep them separate from generic waste."),
                ("Can I order by total linear feet?", "A supplier may need stock lengths and bundle details, so provide the cutting plan when possible."),
            ],
        },
        {
            "slug": "renovation-material-takeoff-checklist",
            "title": "Renovation Material Takeoff Checklist",
            "category": "Renovation Budget",
            "topic": "renovation",
            "parent": "renovation-cost-calculator",
            "description": "Build a renovation material takeoff by room, surface, product, package size, waste, labor, delivery and contingency.",
            "answer": "A renovation takeoff is more reliable when every quantity is tied to a room, surface and product rather than one whole-house guess. List measurements, units, product coverage, package size, waste, labor, delivery, tax, disposal and contingency separately, then link each material line to a calculator or supplier quote.",
            "steps": [
                ("List rooms and surfaces", "Record floors, walls, ceilings, trim, doors, windows and demolition areas by room."),
                ("Assign a product", "Choose the material or finish category and capture its current coverage, yield or package size."),
                ("Calculate purchase quantities", "Add waste and round to complete packages, stock lengths or delivery quantities."),
                ("Build the budget", "Separate material, labor, delivery, permits, disposal, tax and contingency so omissions are visible."),
            ],
            "formula": "project budget = material + labor + delivery + disposal + permits + tax + contingency",
            "example": "A room-by-room takeoff can show why two projects with the same floor area differ: one may include more wall finish, trim, demolition, delivery, access work or contingency.",
            "mistakes": "Using floor area as a proxy for every surface, mixing material and labor in one rate, forgetting delivery and disposal, and applying one waste percentage to every product.",
            "faqs": [
                ("How detailed should a renovation takeoff be?", "Detailed enough that every major surface and cost can be traced to a measurement, product, quote or explicit allowance."),
                ("Should labor be included in material calculators?", "Keep labor separate so the user can compare supplier material costs with contractor or DIY scope."),
                ("What contingency should I use?", "Use a project-specific allowance based on uncertainty and hidden conditions; it is not a substitute for inspection."),
            ],
        },
    ]
