def seo_pages():
    return [
        {
            "slug": "deck-mud-calculator",
            "title": "Deck Mud Calculator — Dry Pack Mortar Quantity",
            "category": "Concrete & Masonry",
            "parent": "cmu-mortar-calculator",
            "description": "Estimate dry-pack deck mud volume and bags from length, width, depth, waste and bag yield for shower pans and tile bases.",
            "formula": "dry-pack volume = length × width × depth; bags = adjusted volume ÷ labeled bag yield",
            "example": "A 4 ft × 4 ft area with an average 2 in bed is about 2.96 ft³ before waste. The final bag count depends on the yield printed on the selected dry-pack or mortar product.",
            "uses": ["Shower pan mortar beds", "Sloped tile bases", "Small dry-pack repairs", "Tile underlayment planning"],
            "faqs": [
                ("What is deck mud?", "Deck mud is a relatively dry sand-and-cement mortar used for applications such as shower-pan beds and tile bases. Follow the selected product or system instructions."),
                ("How deep should deck mud be?", "Depth and slope depend on the project system, drain, substrate and applicable requirements. Enter the designed or specified depth."),
                ("Can I use concrete yield for deck mud?", "Do not assume the same yield. Use the actual dry-pack or mortar product yield and keep the assumption visible."),
            ],
        },
        {
            "slug": "marble-quantity-calculator",
            "title": "Marble Quantity Calculator",
            "category": "Flooring & Tile",
            "parent": "tile",
            "description": "Calculate marble tile pieces and boxes from surface area, tile dimensions, waste and tiles per package.",
            "formula": "pieces = ceil((surface area × (1 + waste)) ÷ tile face area); boxes = ceil(pieces ÷ pieces per box)",
            "example": "A 60 ft² surface using 12 in × 24 in marble and 12% waste needs 67.2 ft² of planned coverage before converting the result to complete pieces or boxes.",
            "uses": ["Marble floors", "Bathroom walls", "Kitchen backsplashes", "Feature walls"],
            "faqs": [
                ("How much extra marble should I buy?", "Use the layout, pattern, veining, cuts and installer plan to set waste. Complex layouts need more than a simple rectangle."),
                ("Should I calculate by square feet or pieces?", "Calculate the covered area first, then convert to pieces and complete boxes using the actual tile size and package information."),
                ("Does this include matching veining?", "No. Vein matching and directional layout can increase waste and should be discussed with the installer or supplier."),
            ],
        },
        {
            "slug": "self-leveling-calculator",
            "title": "Self-Leveling Underlayment Calculator",
            "category": "Flooring & Tile",
            "parent": "flooring",
            "description": "Estimate self-leveling underlayment volume and bags from floor area, average depth, waste and product yield.",
            "formula": "volume = area × average depth; bags = adjusted volume ÷ labeled bag yield",
            "example": "A 200 ft² floor at an average 1/4 in depth is about 4.17 ft³ before allowance. Bag count depends on the product yield and the actual low and high spots.",
            "uses": ["Uneven subfloors", "Tile preparation", "Vinyl flooring preparation", "Small leveling repairs"],
            "faqs": [
                ("How do I measure average depth?", "Measure multiple points across the floor and use the designed or product-approved average depth rather than one low spot."),
                ("Does self-leveler actually level every floor?", "The substrate must be prepared, primed and suitable for the selected product. Follow the manufacturer's limits and installation method."),
                ("Why can bag count change so much?", "Average depth, floor porosity, product yield, mixing loss and edge containment all affect the result."),
            ],
        },
        {
            "slug": "floor-mud-calculator",
            "title": "Floor Mud Calculator — Mortar Bed Quantity",
            "category": "Concrete & Masonry",
            "parent": "cmu-mortar-calculator",
            "description": "Estimate floor-mud mortar volume and bags for tile beds, shower floors and other measured mortar-bed areas.",
            "formula": "mortar-bed volume = area × average thickness; bags = adjusted volume ÷ labeled yield",
            "example": "A 5 ft × 6 ft floor at a 1.5 in average bed is about 3.75 ft³ before waste. Confirm the product yield and required slope before purchasing.",
            "uses": ["Tile mortar beds", "Shower floors", "Mud-set floors", "Small repair areas"],
            "faqs": [
                ("Is floor mud the same as concrete?", "No. Floor mud or dry-pack mortar has different proportions, workability and product instructions. Use the specified mix."),
                ("How do I handle a sloped shower floor?", "Use the designed average or split the floor into sections if the thickness changes substantially."),
                ("Does the calculator design the shower pan?", "No. Drain, waterproofing, slope, substrate and system requirements need qualified installation guidance."),
            ],
        },
        {
            "slug": "tuckpointing-calculator",
            "title": "Tuckpointing Mortar Calculator",
            "category": "Concrete & Masonry",
            "parent": "cmu-mortar-calculator",
            "description": "Estimate tuckpointing or repointing mortar volume from joint length, joint width, depth, waste and product yield.",
            "formula": "mortar volume = joint length × joint width × joint depth; bags = adjusted volume ÷ labeled yield",
            "example": "A 500 linear-foot joint run at 3/8 in wide and 3/4 in deep is about 0.37 ft³ before waste. Actual yield depends on joint preparation and the mortar product.",
            "uses": ["Brick repointing", "Stone joints", "Masonry repairs", "Historic mortar maintenance planning"],
            "faqs": [
                ("How deep should joints be removed?", "Remove deteriorated material only as required by the repair specification and use suitable tools and safety practices."),
                ("Can I use any mortar for tuckpointing?", "No. Mortar compatibility, strength, color and historic masonry requirements matter. Follow the repair specification."),
                ("Why is the real quantity higher than the joint volume?", "Irregular joints, overfilled joints, cleanup, breakage and preparation loss can increase consumption."),
            ],
        },
        {
            "slug": "concrete-screed-calculator",
            "title": "Concrete Screed Calculator",
            "category": "Concrete & Masonry",
            "parent": "concrete",
            "description": "Estimate concrete volume for a screed-formed slab or pour from length, width, thickness, waste and order rounding.",
            "formula": "concrete volume = length × width × thickness; order volume = volume × (1 + waste)",
            "example": "A 20 ft × 12 ft pour at 4 in is about 2.96 yd³ before the selected ordering allowance. Confirm the final order with the supplier and placement crew.",
            "uses": ["Slab screeding", "Garage pads", "Patios", "Driveway sections"],
            "faqs": [
                ("What does screed mean in concrete work?", "A screed is used to strike off and level freshly placed concrete; the required concrete quantity still comes from the pour geometry."),
                ("Does screeding change the concrete volume?", "No. Screeding affects placement and finishing, while quantity comes from the actual pour dimensions and thickness."),
                ("Should I include a waste allowance?", "Usually keep an explicit allowance for measurement variation, subgrade irregularity and placement loss, then confirm supplier order increments."),
            ],
        },
    ]
